### ISSUE TITLE
Error when running on Raspbian

### ISSUE THREAD

**Issue by drinu276** [mrworf/plexupdate#100]
I have a Plex server set up on Raspbian Jessie, and I'm trying to get this script to work. I've set all the options I need, but when I attempt to execute it, I get the "ERROR: You must execute this script with BASH" error.

I'm still relatively new to Linux, and bash, even though I use them on a daily basis, so any help would be greatly appreciated.

**Comment by mrworf** [comment]
How are you executing the script? Like so ```./plexupdate.sh``` (without or without options) or are you doing ```sh plexupdate.sh``` ? If the latter, please replace ```sh``` with ```bash``` since this script relies on bash-isms to work properly :) Let me know how it goes.

**Comment by drinu276** [comment]
Thanks for the reply :)

I have a new error when running "bash plexupdate.sh -p -a":

"Finding download URL to download...OK
ERROR: Unable to retrieve the URL needed for download (Query DISTRO: ubuntu, BUILD: linux-ubuntu-armv7l)"

**Comment by mrworf** [comment]
You should run ```bash plexupdate.sh -l``` and see which distro and build that would work for you. It will show all supported builds by plex.tv

**Comment by mrworf** [comment]
I'm assuming that you resolved the issue and thus I'm closing it. If you're still seeing problems, please reopen it.

**Comment by rowdya22** [comment]
I'm also running on Raspbian. What distro and build did you end up using?
