### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by Baswazz** [mrworf/plexupdate#101]
Does it update when people are people are streaming/using Plex?

**Comment by mscreations** [comment]
No. The script checks to see if anyone is using Plex at the time and will not update if they are.

**Comment by mrworf** [comment]
You can make it check if plex is in-use by defining the ```PLEXSERVER``` option, otherwise it will update regardless of what's going on.

I typically run it from cron at like 4 or 5am in the morning when I know noone is using it :)

Please close this issue if it answers your question.
