### ISSUE TITLE
Automatic script update

### ISSUE THREAD

**Issue by arjankuijpers** [mrworf/plexupdate#11]
Is there a possibility to make this script auto updating, for example every time the user runs the script it will download a new version if available. Could be directly from github.

I'm not into bash script or Linux programming, but I can take a look if I can make a start.

**Comment by mrworf** [comment]
Fun challenge, so I did it. Checkout the -u option. Requires git for it to work. Let me know if there are any issues.

**Comment by xombiemp** [comment]
I tried this out and it says:
You have made changes to the script, cannot auto update
because I filled in my credentials for plex pass I guess.

**Comment by mrworf** [comment]
Yes, you should create a file in the home directory called ".plexupdate" where you fill in your username and password. This way you don't need to edit the script :)

**Comment by xombiemp** [comment]
Ah, of course. Thanks!
