### ISSUE TITLE
Could we get the time/date output added?

### ISSUE THREAD

**Issue by stephen-d-hill** [mrworf/plexupdate#111]
Useful for use in cron and adding output to a log

**Comment by mscreations** [comment]
Where do you mean? Like the log filename should include the date or output the date at the top of the log? Or keep the log statically named, but append the date before each entry in the file?

My vote would probably be for either the last option or the filename with the date option. Not sure which would be better.

**Comment by stephen-d-hill** [comment]
My vote would be for the last option.
