### ISSUE TITLE
Force update when PMS is in use

### ISSUE THREAD

**Issue by dkerlee** [mrworf/plexupdate#114]
Roku players don't have an off switch are are frequently "watching" the last five seconds of a show for days on end.

`Server 127.0.0.1 is currently being used by one or more users, skipping installation. Please run again later`

I'd like to be able to set an option to override that flag.

**Comment by mscreations** [comment]
In your .plexupdate file delete the PLEXSERVER line and it will not check before updating.

**Comment by mrworf** [comment]
What he said... Defining PLEXSERVER is to explicitly to get the feature you're now asking not to have :)
