### ISSUE TITLE
modify logging

### ISSUE THREAD

**Issue by dkerlee** [mrworf/plexupdate#115]
I'd like to have an option to specify log location and log detail.

**Comment by mscreations** [comment]
You can override the log location from your .plexupdate file. If you set the FILE_STDOUTLOG variable to be the path to the file you want for the log, it should work. Keep in mind though that this will NOT remove the file that get's created originally (in /tmp named plexupdate.log.XXXX). If you wanted to, you could include the following in .plexupdate to eliminate that problem:

`if [ -f ${FILE_STDOUTLOG} ]; then rm ${FILE_STDOUTLOG}; fi`
`FILE_STDOUTLOG=<new path the your logfile>`

As for setting the log detail, logging is currently only for when the script runs as a cron job (with the -c option), and as such is fairly limited. I do have an idea on how to change the script to enable better logging and/or messages, but I have to find time to implement it.
