### ISSUE TITLE
plexupdate reporting deprecated usage of config file, even if using --config

### ISSUE THREAD

**Issue by Isilorn** [mrworf/plexupdate#116]
After last update I'm calling plexupdate with the "--config" option but it's still reporting a deprecated usage :

`root@plex:/usr/local/share# /usr/local/share/plexupdate/plexupdate.sh --config /usr/local/etc/plexupdate.config
WARNING: Specifying config file as last argument is deprecated. Use --config <path> instead.`

**Comment by mrworf** [comment]
Should be fixed, please test and close

**Comment by Isilorn** [comment]
Hello

Working thanks !
