### ISSUE TITLE
line 160: [: too many arguments

### ISSUE THREAD

**Issue by Mantene** [mrworf/plexupdate#118]
I pulled the latest version today and followed the instructions. Ran the full command with email pass dldir and saveconfig options. It wrote out a new .plexupdate file. now, whenever I run plexupdate I get "line 160: [: too many arguments"

**Comment by mscreations** [comment]
Are you using the default config file location? (~/.plexupdate)

To run the script the second time, do you have any arguments?

**Comment by mscreations** [comment]
I think i know what's going on. As a workaround, specify the config file. 

Run `sudo ./plexupdate.sh --config ~/.plexupdate`

I'm not near a computer to fix it but will do so later.

**Comment by Mantene** [comment]
Yep, that command works fine. Thanks.

**Comment by mscreations** [comment]
I pushed a commit to fix this issue. Somehow I missed it when I fixed #116 .

**Comment by Mantene** [comment]
Perfect!
