### ISSUE TITLE
Can't Login with correct credentials

### ISSUE THREAD

**Issue by rpicking** [mrworf/plexupdate#122]
Not sure when this started as previously I was using public but cannot login with correct credentials.  I also get an error message line 278: Oh: command not found running it fresh for the first time.

**Comment by mrworf** [comment]
Did you enclose the password and/password with quotes? See FAQ at the end of the README.md for details. Sounds like you have a quote or something in the credentials :)

**Comment by rpicking** [comment]
lmao I saw that and I thought I was really clever and did that when running the setup.  Right after I posted this I checked the config file and saw that it saved it improperly and realized I should have checked that before posting an issue which was pretty dumb of me.
