### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by boistordu** [mrworf/plexupdate#126]
Hi 
`Authenticating...ERROR:` Username and/or password incorrect`
test with single quote, double quote. nothing works... any idea? 

and i've tried to connect with curl and jq and it works with my mail and password so I don't really understand here the problem.

**Comment by mscreations** [comment]
Without posting your password, what special characters are in your password? And you're using the single quote, right? PASS='myPa$$word' 

Is the script updated? If so, can you post the contents of /tmp/plexupdate.log (check to make sure your password is not in there though)

**Comment by boistordu** [comment]
$ and ! 
is that PASS un uppercase or pass in lowercase ? because in you command line you put email and pass in lowercase....

**Comment by boistordu** [comment]
and for the log I will try but not sure still how to do that since I'm using your app in a docker container

**Comment by boistordu** [comment]
where should be your logs?

**Comment by boistordu** [comment]
nevermind found it. 
nothing really in your log:
```
2016-10-26 00:20:49 - INFO: ##### Begin PlexUpdate #####
2016-10-26 00:20:49 - INFO: Args: --email=   --pass= -a -d
2016-10-26 00:20:49 - INFO: Authenticating...
2016-10-26 00:20:50 - ERROR: Username and/or password incorrect
```
so in the log there was no quote at all I don't know if it's normal.
By the way, I've use a + in my adress mail.

**Comment by mscreations** [comment]
since this is in docker, are you using an environment variable to set the password that you pass to docker at runtime? Like docker run -e PASS='pa$$word!' ? I'd think this setup might be better off if you created a .plexupdate file and copied it over in the dockerfile. 

I'm wondering if that could be what is losing the password.

**Comment by boistordu** [comment]
I had this idea too but apaprently this is not the problem since I have modified the dockerfile and put it in 

/plexupdate/plexupdate.sh --email='....' --pass='....' -a -d

so if I'm not wrong it execute the script directly.... or maybe it does something bad....

**Comment by mscreations** [comment]
Try creating a .plexupdate file that has EMAIL='your username' and PASS='your password' and then in your dockerfile copy it to the container. Then when you run the script, pass the location in the --config parameter. 

ex:

`cp .plexupdate /root/.plexupdate`
`/plexupdate/plexupdate.sh --config /root/.plexupdate -a -d`

**Comment by boistordu** [comment]
ok and is it the username or the pass?

**Comment by boistordu** [comment]
with the config file it works ... don't know exactly what'sthe problem here then...

**Comment by mscreations** [comment]
i think i know what might be happening. Try applying this patch file and see if it corrects the issue.
[patch.diff](https://gist.githubusercontent.com/mscreations/43a04c430b53c877a11c72365d04fc2a/raw/282c00a49d073897da9ab743e59e2d5d08f793ea/patch.diff)

After saving the file to your plexupdate folder, run: `git apply patch.diff`

**Comment by boistordu** [comment]
fatal: corrupt patch at line 21

**Comment by boistordu** [comment]
maybe it s a problem with my dockerfile but I've just rearrange 
and done 
```
RUN git clone --depth 1 https://github.com/mrworf/plexupdate.git /plexupdate
ADD ./patch.diff /root/patch.diff
RUN git apply /root/patch.diff
```
so shouldn't be a problem

**Comment by boistordu** [comment]
I me doing some verification about my code, it was an error before but it still seems that the file is corrupted at lien 21 and don't know why since I do'nt know how doing diff patch in git

**Comment by mscreations** [comment]
Try it again. I think it was missing an end of line. Darn copy and paste.

**Comment by boistordu** [comment]
the file is better but It seems that I have a problem on my part where the file is not at the good place or something like that

**Comment by mscreations** [comment]
okay, try cloning from my repo:

`git clone -b login-issue https://github.com/mscreations/plexupdate.git`

The `-b login-issue` is necessary because it is the only branch you want.

**Comment by boistordu** [comment]
ok. a precision from before, the patch has been applied seems to but after it wasn't able to launch plexupdate. very strange. Anyway I will take your branch now.

**Comment by boistordu** [comment]
it's working :) just had auth successful.

**Comment by boistordu** [comment]
what was the problem exactly?

**Comment by mscreations** [comment]
when you enter the email and password on the command line, there was an eval that copied the data from one variable to another in a loop. I unrolled the loop to fix it. Probably should eliminate it altogether. I'll fix it up the right way in a little bit and submit a pull request to close this issue. Then you should be able to just clone mrworf's repo again.

**Comment by boistordu** [comment]
mmmmh so the treatment of env var then ok. Big Big Thanks anyway 👍

**Comment by mscreations** [comment]
I created a pull request to fix this issue. I found that there was a missing set of single quotes in the eval line. Didn't need to unroll the loop, so this more correctly fixes the issue.

**Comment by boistordu** [comment]
thanks. I guess it was at the mail adress that quotes were missing then .  thanks for everything
