### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by forceindia26** [mrworf/plexupdate#13]
I am on Ubuntu 14.04.2 when running the script with sudo sh plexupdate.sh i get:

plexupdate.sh: 92: [: no: unexpected operator
plexupdate.sh: 121: [: unexpected operator
plexupdate.sh: 126: [: no: unexpected operator
plexupdate.sh: 149: plexupdate.sh: Syntax error: Bad for loop variable

I've added the .plexupdate file under my home dir with my login details

Is there anything i can do?

Thanks

**Comment by SpaceK33z** [comment]
That's because this is a bash script. Run it with `sudo bash plexupdate.sh`.

**Comment by mrworf** [comment]
Agreed, this script requires bash. I usually run it using "sudo ./plexupdate.sh" (as long as the eXecute bit is set on the file) which will automatically invoke bash.
