### ISSUE TITLE
Special characters in Password.

### ISSUE THREAD

**Issue by jaarsa** [mrworf/plexupdate#130]
Hi!

I have characters like : and) in my password, and it seems like the script chrashes.

pass="xxxxx)xx"

./plexupdate.sh: eval: line 354: syntax error near unexpected token `)'
./plexupdate.sh: eval: line 354:`PASS=xxxxx)xx'
Authenticating...ERROR: Username and/or password incorrect

**Comment by jaarsa** [comment]
Not working with 'xxxxx)xx' either

**Comment by mscreations** [comment]
Pull request #127 should fix this.

**Comment by dvdmuckle** [comment]
This doesn't seem to work with `!` characters. Using a `!` in a password results in `-bash: !xxxxx: event not found`, where `xxxxx` is the rest of the password after the `!`.

**Comment by jaarsa** [comment]
@dvdmuckle just curious, but did you update to latest script #127 ?
Try to use you use ' instead of ".

I edited line 354 like @mscreations noted, and it worked for me too.

**Comment by mscreations** [comment]
@dvdmuckle I am curious as well if the script is updated. All checks on my end work with a fresh clone work fine with any special characters (other than a single quote) as long as the passwords are quoted with single quotes (eg 'pass!@word' instead of "pass!#word").

**Comment by dvdmuckle** [comment]
I didn't try single quotes, only doubles. I'll try that and let you know what happens.

**Comment by dvdmuckle** [comment]
That didn't work either, same error.

**Comment by mrworf** [comment]
Are you seeing this on the same line in the script? 

If you don't get any linenumbers, please run script using this method :

bash - x plexupdate.sh 

And it will print a ton of debugging but should show where it fails and what it did before that.

**Comment by dvdmuckle** [comment]
Oh, executing the script with `bash plexupdate.sh` as well as the required email and password conf actually worked, it didn't trip up on the special character. Awesome! Perhaps this should be added to the Readme.

**Comment by mrworf** [comment]
Running with bash on command line or executing via #!/bin/bash (ie, running script as a command) should yield the same results. What exactly did you do that worked (provide commandline with obfuscated password/username) so we can figure out why this worked :) 

Also, what distro are you using and what shell are you using?

**Comment by dvdmuckle** [comment]
Using Ubuntu 16.04, I did `bash plexupdate.sh --email='my@email.com' --pass='MyPass!Word'`

**Comment by mrworf** [comment]
And if you skip --email --pass it does not work? (Just so I understand the situation :))

**Comment by dvdmuckle** [comment]
`Authenticating...ERROR: Username and/or password incorrect`

**Comment by mrworf** [comment]
And which special chars are in username and which are in the password? And does your config file contain anything else than these two items (and have you made sure that there is a line-ending on the last line) ?

**Comment by dvdmuckle** [comment]
Just a @ in the email and a ! in the password. There didn't appear to be any line ending when the `--saveconfig` flag was used when executing the script with `bash plexupdate.sh --email='my@email.com' --pass='MyPass!Word'`, it just stops after `PLEXPORT=32400`

**Comment by mrworf** [comment]
What happens if you add the line-ending?

**Comment by dvdmuckle** [comment]
Sorry, what would that look like? The config worked fine without the line-ending.

**Comment by mrworf** [comment]
Was just thinking that the password issue would somehow be related to missing line ending.

**Comment by dvdmuckle** [comment]
The password issue is when there's no config (no .plexupdate), and the --pass is taken in as a command line argument.

**Comment by mrworf** [comment]
Ah, my bad. I jumped into it in the middle so I might have had the wrong context. 

But what essentially, the --pass stuff works, but only if you explicitly run it using bash from the command line. If you omit bash, then it does not work?

If that's the case, can you run ```which bash``` and see what path it returns. Likewise, are you using something other than bash as your standard shell?

**Comment by jaarsa** [comment]
This is my  line, if it could be any help:
plexupdate.sh --email="xxxx@gmail.com" --pass="xxxxx:)xx" --dldir="/home/plexupdate" -a -d --saveconfig

**Comment by jaarsa** [comment]
I did not need the ' on password, after changing line 354

**Comment by dvdmuckle** [comment]
@mrworf it returns /bin/bash, I don't have any other shells installed.

**Comment by mscreations** [comment]
I think i found the problem but am not near a computer to fix it

**Comment by dvdmuckle** [comment]
That seems to have only made things worse. It reports an authentication error despite the email and password being right. This happens both with `sudo ./plexupdate.sh` and `sudo bash plexupdate.sh`, with the email and password both being supplied as command line arguments.

**Comment by mscreations** [comment]
Try deleting all the files and starting over. If the config file was done wrong before it only gets worse with this.

Try a fresh pull, delete your .plexupdate file, and delete /tmp/plexupdate.log. Run the script as new and then if it errors out, post your log file (after editing out your password). Also, what special characters in your password are directly next to each other?

**Comment by dvdmuckle** [comment]
`dvdmuckle@hermit-purple:~$ cat /tmp/plexupdate.log
2016-11-04 18:01:30 - INFO: ##### Begin PlexUpdate #####
2016-11-04 18:01:30 - INFO: Args: email=xxxxxxxxxx --pass=xxxxxxxxxx --saveconfig
2016-11-04 18:01:30 - INFO: Using "dvdmuckle" configuration: /home/dvdmuckle/.plexupdate
2016-11-04 18:01:30 - INFO: Authenticating...
2016-11-04 18:01:30 - ERROR: Username and/or password incorrect`

The issue might be that it's still using the .plexupdate config even though I deleted it. Also, there is only one special character in my password, a `!`.

**Comment by mscreations** [comment]
If you are comfortable editing the file, try adding the following at Line 411 (before `if [ "${SHOWPROGRESS}"...`)

```echo $EMAIL```
```echo $PASS```
```exit 1```

When you run it, it will spit out the email and password that it has after doing any kind of processing (these variables are not changed after this point). If they don't match we have an issue somewhere.

Make sure to take the lines back out or the script will never finish (the exit 1 line will kill the script)

**Comment by dvdmuckle** [comment]
That did spit out my password, but for whatever reason my email wasn't there either. Should I have used $EMAIL_CL instead?

**Comment by mscreations** [comment]
No, $EMAIL_CL is what is entered on the command line. $EMAIL is read first from the config file and then if $EMAIL_CL is not empty $EMAIL gets overwritten with the value from $EMAIL_CL. It might be worthwhile to add `echo $EMAIL_CL` in before the `echo $EMAIL` line to see if something is happening to that variable to mangle it. At least we know the password is working ok.

**Comment by dvdmuckle** [comment]
Ah, sillly me, I didn't add the flag properly to the command line argument. Everything works now! Sorry to be a bother.

**Comment by mscreations** [comment]
glad it is working for you.
