### ISSUE TITLE
Version number.

### ISSUE THREAD

**Issue by jaarsa** [mrworf/plexupdate#135]
This is not an issue, more like an option.

Is it possible to add an option -v like ./plexupdate -v so that you can see what version of plexupdate you are on.

**Comment by mrworf** [comment]
While that's a good idea, the problem is that anyone making a change would have to update it. It's all too prone to human error. If you use git clone, you can rely on the changelog (git log) which is more reliable and also affords you the capability of doing an automatic update.

**Comment by mscreations** [comment]
If you want a version number to reference, the best would be if you just ran `git rev-parse --short HEAD` to get the short hash of the current commit.

**Comment by mrworf** [comment]
Latest version of the script is able to detect if your local version is out-of-date (even if you're not using git) and notify you. That's the best I can do. Please give it a go :)
