### ISSUE TITLE
Script not working for me

### ISSUE THREAD

**Issue by justinglock40** [mrworf/plexupdate#136]
[root@localhost ~]# plexupdate/plexupdate.sh -p -a
plexupdate/plexupdate.sh: line 497: cd: ‘’: No such file or directory
ERROR: Download directory does not exist or is not a directory

**Comment by ultimate255** [comment]
Define dldir
Which would be the folder you want the updates to download in
`./plexupdate.sh dldir='~/Downloads/plexupdate'`

Or you can put a dot, if you want it on the same folder as plexupdate.
`./plexupdate.sh dldir='.'`

You can also edit line 126 of plexupdate.sh and specify the download directory there.

**Comment by mrworf** [comment]
Typically I'd discourage editing the script itself, you can either use the commandline options or edit the .plexupdate configuration file to override the defaults.

But I'm curious as to why this wouldn't work. Are you running latest version of the script and do you by chance have a .plexupdate configuration file? And has this worked before?

**Comment by ultimate255** [comment]
I also get the same issue with the latest version.
`./plexupdate.sh: line 497: cd: /a/folder/to/save/the/files/in: No such file or directory
ERROR: Download directory does not exist or is not a directory
`
When dldir is not specified.

**Comment by mrworf** [comment]
But does the "/a/folder/to/save/the/files/in" exist? By default, the DOWNLOADDIR setting points towards "." which is the same as the folder you're executing in. If you set it to blank or non-existent folder, then it will fail. Do you have a .plexupdate config file and if so, what's the value of DOWNLOADDIR?

**Comment by justinglock40** [comment]
When I first downloaded it. That was the given directory. However it still failed using both the command line edits as well as the trying to edit the script itself.

**Comment by justinglock40** [comment]
When I looked for a configure file it did not exist

**Comment by ultimate255** [comment]
I do not have a config file.
`./plexupdate.sh --email='my.email@plex-server.com' --pass='my-secret-plex-password' --saveconfig`
Even if I do not set dldir in the commandline (see above), it still leads to the same error.
I have to set it to a dot or specify a directory.

**Comment by mrworf** [comment]
I just recreated the scenario described, brand new plexupdate in root's home folder and ran it with -p and -a:

````root@pms:~# plexupdate/plexupdate.sh -p````
````Finding download URL...OK````
````Downloading release "plexmediaserver_1.2.7.2987-1bef33a_amd64.deb"...OK````
````root@pms:~# plexupdate/plexupdate.sh -p -a````
````Finding download URL...OK````
````File already exists (plexmediaserver_1.2.7.2987-1bef33a_amd64.deb), won't download.````

Even if I run it with ```./plexupdate.sh --email='my.email@plex-server.com' --pass='my-secret-plex-password' --saveconfig``` it works as expected. 

What platform are you running this on? I've been testing on Ubuntu 16 on intel 64bit.

**Comment by justinglock40** [comment]
Fedora 23 (64-bit)

**Comment by ultimate255** [comment]
```
ultimate55@ultimate255:~/Downloads$ plexupdate/plexupdate.sh -p
plexupdate/plexupdate.sh: line 497: cd: /a/folder/to/save/the/files/in: No such file or directory
ERROR: Download directory does not exist or is not a directory
ultimate55@ultimate255:~/Downloads$ plexupdate/plexupdate.sh --email='my.email@plex-server.com' --pass='my-secret-plex-password' --saveconfig
plexupdate/plexupdate.sh: line 497: cd: /a/folder/to/save/the/files/in: No such file or directory
ERROR: Download directory does not exist or is not a directory
ultimate55@ultimate255:~/Downloads$ 
```
I tried again with a new fresh copy.
Ubuntu 16.10

**Comment by ultimate255** [comment]
LOL, okay found the problem.
I didn't realize PlexUpdate automatically generated a Configuration File in my home directory.
I fixed the DownloadDir from there.

**Comment by mrworf** [comment]
Latest version (as of this VERY moment) will print the configuration file used and also tell you what folder it tried to use as the downloaddir when it fails.

@justinglock40 Please download and test

@ultimate255 Good to hear you figure it out 👍

**Comment by mrworf** [comment]
@justinglock40  I see where you got the path from now, the example in the readme.md. If you copied and pasted that and ran it, it will have created a config file for you, which is why the download directory is wrong. Newest version will show you which config is used and what path is failing.

**Comment by justinglock40** [comment]
So should I clone the git as root and the run which command?

**Comment by mrworf** [comment]
No, you need to delete the config file or edit it to reflect the correct directory and settings. If you update your plexupdate.sh to latest version, it will tell you where it find the configuration file and all you need to do is edit that file.

**Comment by ultimate255** [comment]
@justinglock40 Edit .plexupdate in your Home Directory
It is a hidden file, use CTRL + H to view hidden files.

Set your desired path in DownloadDir.

**Comment by justinglock40** [comment]
So I got the script to run, but I can't find the config file. and how to do i set it to automatically check say daily for script and plex-pass update

**Comment by mrworf** [comment]
Did you update the script? It will tell you if it's loading a configuration file and from where. But regarding your question, you need to set up cron to run the script at the desired interval.

**Comment by justinglock40** [comment]
I ran this and this is what I got:

[jwashington@localhost ~]$ sudo plexupdate/plexupdate.sh -p -u -a
Auto updating...OK
Finding download URL...OK
WARNING: Your distribution may require the use of the AUTOSTART [-s] option for the service to start after the upgrade completes.
Your OS reports the latest version of Plex (plexmediaserver-1.2.7.2987-1bef33a.x86_64) is already installed. Use -f to force download.
[jwashington@localhost ~]$

**Comment by mrworf** [comment]
Cool, then all you need to do is to add it to a cronjob :)

**Comment by justinglock40** [comment]
I still can't find the config file to set my options such as autostart. And do you know how I would setup a cronjob? I've never done that before.

**Comment by justinglock40** [comment]
Ok so i choose to do the systemd route. how do I make it pull the plexpass version instead of the public release?

**Comment by mrworf** [comment]
Check the readme.md, it details on how to configure it to use your login credentials to pull the plexpass version instead.

**Comment by justinglock40** [comment]
Ok so I got that part going but my output from my terminal doesn't look like what yours looks like in the wiki. This is the output is this correct? and then will I just check plexupdate.log to see if it runs at midnight?

[jwashington@localhost ~]$ systemctl status plexupdate.timer -l
● plexupdate.timer - Run the plex updater daily
   Loaded: loaded (/etc/systemd/system/plexupdate.timer; enabled; vendor preset: disabled)
   Active: active (waiting) since Sun 2016-11-13 12:30:41 CST; 30min ago

Nov 13 12:30:41 localhost.localdomain systemd[1]: Started Run the plex updater daily.
Nov 13 12:30:41 localhost.localdomain systemd[1]: Starting Run the plex updater daily.
[jwashington@localhost ~]$ systemctl status plexupdate
● plexupdate.service - plexupdate
   Loaded: loaded (/etc/systemd/system/plexupdate.service; static; vendor preset: disabled)
   Active: inactive (dead)

**Comment by justinglock40** [comment]
is there anyway to clear this? 

2016-11-15 00:00:00 - INFO: ##### Begin PlexUpdate #####
2016-11-15 00:00:00 - INFO: Args: -a -c -d -s -u
2016-11-15 00:00:00 - ERROR: You have made changes to the script, cannot auto update
2016-11-16 00:00:00 - INFO: ##### Begin PlexUpdate #####
2016-11-16 00:00:00 - INFO: Args: -a -c -d -s -u
2016-11-16 00:00:00 - ERROR: You have made changes to the script, cannot auto update

**Comment by mrworf** [comment]
Yes, either don't ask it to autoupdate (-a) or avoid changing the script. Auto update simply does not work if you change the script itself.

**Comment by justinglock40** [comment]
i removed the -p flag also because that said it was for the public download. So does removing that allow the plex pass download?

**Comment by mrworf** [comment]
This is what you'll do:

Create a file somewhere on your linux machine (perhaps same directory as plexupdate.sh ?) with the following:
```
USER='<your plex email address>
PASS='<your plex password>'
DOWNLOADDIR='<whereever you want the files to be saved>'
AUTOINSTALL=yes
AUTOSTART=yes
AUTODELETE=yes
CRON=yes
```

Next, you edit the line which launches ```plexupdate.sh``` so the ONLY arguments you give it are:
```--config <the path and filename for the file you just created>```

This should work, please give it a try. 

**NOTE!** 
All filename and directory references mentioned above *MUST* be absolute, ie, if the file is in the home directory of user "john" and the file is called ```plexupdate.conf``` the path would be ```/home/john/plexupdate.conf```

Also, the email/password is referred to above is the email/password you use to login to https://plex.tv/

**BONUS!**
If you restore ```plexupdate.sh``` to original (using for example, ```git checkout -- plexupdate.sh``` in the plexupdate folder) you will be able to turn on auto update by adding the line

```
AUTOUPDATE=yes
```

To your config file.

**Comment by mrworf** [comment]
Given your new issue, I'm assuming that we can close this one now?

**Comment by justinglock40** [comment]
Yes this can be closed and I did ensure that my access information was correct
