### ISSUE TITLE
Username and/or password incorrect

### ISSUE THREAD

**Issue by justinglock40** [mrworf/plexupdate#139]
So I have everything set up and running, but when I try to get it to pull the Plex Pass version it says that the username and password are incorrect regardless if i use " or '. Any ideas what may be causing this?

**Comment by mrworf** [comment]
I know this is going to sound stupid, but you've tried copy'n'pasting the username and password from the configuration file into the login box for https://plex.tv just to be sure?

Also, while I think they say you can use the username, my experience is that it's better to use the email address which is associated with your account.

**Comment by mrworf** [comment]
I've updated plexupdate with an option to print out the email/password used for accessing plexpass versions. Also fixed a bug where it wouldn't tell you that email/pass were blank.

Please update and try again. Run ```plexupdate.sh``` with the ```-v``` option added to see the password and email used when it failed to authenticate. Just to rule out any issues.

**Comment by justinglock40** [comment]
Got this: 

[root@HDA ~]# plexupdate/plexupdate.sh -u
Auto updating...remote: Counting objects: 6, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 4), reused 4 (delta 2), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/mrworf/plexupdate
   1b98ed6..446fe0b  master     -> origin/master
OK
ERROR: Need email & password to download PlexPass version. Otherwise run with -p to download public version.
[root@HDA ~]# nano plexupdate/.plexupdate
[root@HDA ~]# plexupdate/plexupdate.sh -v
ERROR: Need email & password to download PlexPass version. Otherwise run with -p to download public version.
[root@HDA ~]#

**Comment by mrworf** [comment]
Well, there's you problem :) You're not pointing out the configuration file. You did create one, right?

If so, just add ```--config <the path and file>``` and it should work.

**Comment by justinglock40** [comment]
ok that work so do i need to also add that to my systemd timer?

**Comment by mrworf** [comment]
Yes

**Comment by mrworf** [comment]
Please close the issue if it's been resolved and works for you now :)
