### ISSUE TITLE
How to run in Cron?

### ISSUE THREAD

**Issue by thatvalis** [mrworf/plexupdate#143]
Hi, I'm a pretty new linux users (started a few weeks back).

The scripts works great when I run it manually, but I have tried to make it run with cron without success.
I just put it in the crontab with:
sudo crontab -e
0 * * * * /home/plex/plexupdate/plexupdate.sh

Cron succesfully launches the script every hour, but nothing happens.

I have read the readme and tried adding -c at the end like so:
0 * * * * /home/plex/plexupdate/plexupdate.sh -c
But it still doesn't work.
What should I do to make it run with cron?

**Comment by Kezxo** [comment]
This should explain it: https://github.com/mrworf/plexupdate/wiki/Ubuntu%3A-Run-plexupdate.sh-from-cron

**Comment by thatvalis** [comment]
How did I miss that wiki.. That should surely do it, thanks for your help!

**Comment by mscreations** [comment]
Some major changes are coming possibly as soon as today that will change cron usage for the better. It will just involve rubbing an installer that will set everything up for you.
