### ISSUE TITLE
Pointless issue

### ISSUE THREAD

**Issue by MatthewBooth** [mrworf/plexupdate#149]
Sorry, I'll see myself out after this. Just wanted to drop by and say this update with the cronjobs is great. I'd done all this myself, but having it work OOB is fantastic.

Thanks for this script. It's a huge timesaver!

**Comment by demonbane** [comment]
I can't speak for @mrworf, but this is definitely **my** favorite kind of "issue" to read. 😄

I'm glad I was able to contribute and knowing that it's making someone's day a bit easier is really awesome, so thanks for taking the time to say so!

**Comment by mrworf** [comment]
Yes, these issues are awesome! more, please 😺
