### ISSUE TITLE
-s flag not working in Fedora 23.

### ISSUE THREAD

**Issue by justinglock40** [mrworf/plexupdate#151]
So I'm using the -s flag to enable auto restart after an update, but after installation PlexMediaServer still requires me to run: "systemctl start plexmediaserver" despite having the -s flag in my confit file. Am I missing something?

**Comment by demonbane** [comment]
Can you paste the contents of your config file here? Be sure to remove any usernames/passwords if you have them in there.

**Comment by justinglock40** [comment]
Here's my config:

# Config file for plexupdate
DOWNLOADDIR='.'
EMAIL='Removed'
PASS='Removed'
CHECKUPDATE='yes'
PLEXSERVER=192.168.1.10
PLEXPORT=32400
AUTOUPDATE=yes
AUTOINSTALL=yes
AUTODELETE=yes

**Comment by demonbane** [comment]
It looks like you don't actually have `AUTOSTART` in your config (that's the parameter that the -s sets). You can either add `AUTOSTART=yes` to your config or just run `extras/installer.sh` from your plexupdate directory and it will add it for you.

**Comment by demonbane** [comment]
@justinglock40 were you able to get it working?

**Comment by justinglock40** [comment]
Added the flag but no updates have come out to test?
