### ISSUE TITLE
New configuration is not secure

### ISSUE THREAD

**Issue by timrettop** [mrworf/plexupdate#152]
I'm wondering how this new method of storing the configuration in /etc/plexupdate.conf might be more secure. 

The file is created and readable by all, and stores your plex password if you've instructed it to.  Why is this better than storing in the users home directory (.plexupdate)

Could the file at least be set with 600 permissions when created?

**Comment by demonbane** [comment]
I looked at setting the permissions to 600, but this would cause problems for people who aren't running plexupdate as root. 

Instead, I've made the permissions 640 with the owner being set to root, and the group being set to `id -gn`. This way your user can still read the file (and run plexupdate), but modifying it requires root permissions.

**Comment by kyse** [comment]
-rw-r--r-- 1 root root 126 Dec 20 22:53 plexupdate.conf
-rw-r--r-- 1 root root  86 Dec 20 22:53 plexupdate.cron.conf

Yea, no.  Whatever you think you did, the result is not 640.  These passwords should be marked 600 and located in root home dir.

**Comment by demonbane** [comment]
@kyse you have to re-run `extras/installer.sh` for the changes to take effect.
