### ISSUE TITLE
[Feature request] Auto update of plexupdate script

### ISSUE THREAD

**Issue by Antexa** [mrworf/plexupdate#155]
Hi!

First of all thanks for your script, it is very helpful.

Is it possible to implement a function verifying the verison of the script and allowing to update it automatically?

Let me know what you think about it.

Antex

**Comment by Tommatheussen** [comment]
That's already possible, you need to use the `AUTOUPDATE` option.
you do need to have git installed on your machine though

**Comment by Antexa** [comment]
Sorry for this,I didn't notice that option was present.
