### ISSUE TITLE
unable to install on Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by twistedatoms** [mrworf/plexupdate#159]
I pulled the program via git

created a config file 

AUTOINSTALL='yes'
EMAIL='email'
PASS='password'
PUBLIC='no'
AUTOUPDATE='yes'
PLEXSERVER='127.0.0.1'
PLEXPORT='32400'
DOWNLOADDIR='/tmp/'

But I continue to get the following

# /opt/plexupdate$ sudo ./plexupdate.sh -a -P -d
Authenticating with plex.tv
Retrieving list of available distributions
ERROR: Unable to retrieve the URL needed for download (Query DISTRO: ubuntu, BUILD: linux-ubuntu-x86_64)

**Comment by mrworf** [comment]
The first issue I see is that you're telling it to download the plexpass version (PUBLIC="no") but don't provide username/password. Or did you remove that?

**Comment by raidoo9** [comment]
I am getting the same error. I am using public branch. Thanks for your help.

**Comment by mrworf** [comment]
I think Plex.tv has changed their output, I'm getting the same error. Will try to fix asap

**Comment by mrworf** [comment]
Actually, it's broken on plex.tv ... cannot download from them either. URL is set to "#" instead of a real link

**Comment by mrworf** [comment]
I made a slight change, the script will now try to decide if it's a plexupdate.sh issue or plex.tv issue.

**Comment by twistedatoms** [comment]
yes, in the original post I just took out my credentials. obviously didn't want to post them here. so I updated and ran your script again as you see below. then saw the output and went to plex.tv and tried to download it manually, sure enough it won't work. guess I will wait for them to resolve. thank you for adding the extra debug in there.

# /opt/plexupdate$ sudo ./plexupdate.sh -a -P -d
Authenticating with plex.tv
Retrieving list of available distributions
ERROR: Unable to retrieve the URL needed for download (Query DISTRO: ubuntu, BUILD: linux-ubuntu-x86_64)
ERROR: It seems release info is missing a link
ERROR: Please try https://plex.tv and confirm it works there before reporting this issue

**Comment by mrworf** [comment]
It only shows if the script is able to get all but link and checksum, so it's not trying to be snarky :)

**Comment by mrworf** [comment]
Seems to work again, closing this issue.
