### ISSUE TITLE
yum waits for confirmation before update on CentOS

### ISSUE THREAD

**Issue by tb2007** [mrworf/plexupdate#16]
Great work on the script, just fantastic!  I may be running this wrong but yum waits for you to accept the install before it will update the RPM package.

OS:  CentOS 6.6

Scenario: Run .sh script with -a option

Issue:  Script will download and hang on yum install screen.  Waiting for you press "y/n" to accept the new RPM install.

Workaround:  Modify line #285 
From:  sudo yum localinstall "${DOWNLOADDIR}/${FILENAME}"
To: sudo yum -y localinstall "${DOWNLOADDIR}/${FILENAME}"

The -y option auto accepts yum messages.

**Comment by mrworf** [comment]
It's been fixed and pushed. Try it out.
