### ISSUE TITLE
User/Group

### ISSUE THREAD

**Issue by rssw** [mrworf/plexupdate#160]
Hi, I would like to set a custom username and group for plex to run as.  Is this possible, or is only the default plex:plex supported?

I can change the user and group in plexmediaserver.service, but the settings get overwritten on every update of plexupdate.sh

**Comment by demonbane** [comment]
This is actually just a side-effect of how systemd works and not directly related to plexupdate. Since you're editing the service file, every update just overwrites it. To fix this just do `sudo systemctl edit plexmediaserver` and add the following:

```
[Service]
User=yourusername
Group=yourgroupname
```

**Comment by rssw** [comment]
Thanks!
