### ISSUE TITLE
Not detecting new PlexPass update

### ISSUE THREAD

**Issue by frasergr** [mrworf/plexupdate#161]
Apologies in advance if this is not the correct place to be posting this!

Today, there's a new version of PlexPass (1.4.1.3362-77c6a4f80). When running the plexupdate script, it states that I have the current version of 1.3.4.3285-b46e0ea. Does the script require an update to support new versions or does it automatically parse the Plex downloads? Could something have changed on the Plex end of things to prevent detecting the new version?

**Comment by mrworf** [comment]
Please add `PUBLIC=no` to your configuration and it will work. Added a warning to the script so it will tell you about this :)

**Comment by frasergr** [comment]
Thanks for the reply and my mistake. I was under the (incorrect) assumption that having my login details would be sufficient for getting the non-public download.

Modifying the config file to include `PUBLIC=no` worked.

**Comment by mrworf** [comment]
The reason is that you should be able to get the public version if you decide to switch without removing your credentials. Sorry for the confusion.
