### ISSUE TITLE
use Token instead of username/pass

### ISSUE THREAD

**Issue by cyberbrix** [mrworf/plexupdate#162]
Is there a reason that we can't use &X-Plex-Token=<PlexToken> rather than username/pass? I was just scripting a version check (not update, just check version numer) and I found that plex token worked rather than trying to set a cookie, etc.

**Comment by mrworf** [comment]
See #164 ... it was a pending commit which needed some coaxing. Now you should be able to do just that, use the plex server token if available. The cookie stuff remains since we need to be able to obtain a token in the first place if config file isn't available or other weirdness happens.
