### ISSUE TITLE
Feature request: Claim server.

### ISSUE THREAD

**Issue by Hellowlol** [mrworf/plexupdate#168]
Could we add a option to add a claim parameter so it installs and claim the server at the same time? This will be usefull if your running plex on a vps so we dont have to setup a ssh tunnel and browse just to login.

**Comment by mrworf** [comment]
I'm not quite sure what you're asking here. plexupdate requires SSH since it runs on the linux machine which has the server.

**Comment by demonbane** [comment]
@mrworf I think he's referring to the screen that you have to go through when you first set up a new Plex instance on a server. You have to access the site locally via a browser to "claim" the server before it'll really do anything. So if you're setting it up on a headless server you have to forward port 80 to yourself via SSH to be able to access the site "locally" in a browser.

@Hellowlol if you've looked at all of the requests necessary for this to work and if you think it'd be doable just using wget and curl I'd be interested in looking at it, but my guess is that it's going to fall pretty squarely in the "out of scope" category for plexupdate.

**Comment by Hellowlol** [comment]
Ok i think it would be pretty easy but im know nothing about linux. My intension was to run plexupdate in as before_script for https://github.com/pkkid/python-plexapi travis so the tests always run on the latest public version of pms.

I think this should give you a pretty good idea on how to handle this.
https://github.com/plexinc/pms-docker/blob/d1ea49cc79deaad395f8448a606811aafc64d402/root/etc/cont-init.d/40-plex-first-run#L114

**Comment by demonbane** [comment]
I just did a bit more looking around the example that you shared, and it looks like it requires the user to actually get a claim token manually from https://plex.tv/claim first. Since going down this path starts getting into the territory of configuring your Plex server for you, I think it's best left to a separate project since plexupdate is only concerned with updating the plexmediaserver packages.

**Comment by mrworf** [comment]
Closing this as it isn't within the purview of plexupdate.
