### ISSUE TITLE
Keep getting errors trying to run the script

### ISSUE THREAD

**Issue by RacerBas** [mrworf/plexupdate#17]
I made a .plexupdate file with my info in it but i keep getting this:
plexupdate.sh: 92: [: no: unexpected operator
plexupdate.sh: 121: [: bvanlangevelde@gmail.com: unexpected operator
plexupdate.sh: 126: [: no: unexpected operator
plexupdate.sh: 149: plexupdate.sh: Syntax error: Bad for loop variable

Any ideas?

**Comment by mrworf** [comment]
Hmm... did you place your email within quotes or not? I have mine without quotes and it works. Also, you're running the script with bash or just ./plexupdate.sh, correct? (because sh will not work).

**Comment by RacerBas** [comment]
How stupid of me, I did try it with SH. My bad. running it with bash did the trick. Thanks!

**Comment by mrworf** [comment]
No worries :)
