### ISSUE TITLE
No e-mail/No log

### ISSUE THREAD

**Issue by justinglock40** [mrworf/plexupdate#171]
I reinstalled your script with the included installer and enabled "notify", but when the update ran this morning I didn't get an e-mail or a log file written.

Am I missing something?

**Comment by justinglock40** [comment]
Or does the log and email only appear when the cronwrapper runs? not when the script is manually run?

**Comment by demonbane** [comment]
@justinglock40 Exactly. When you run the script manually from the command line you'll get all of the output in the terminal. Logging and email notifications are only for cronwrapper.
