### ISSUE TITLE
Should I keep using this or use the official repo?

### ISSUE THREAD

**Issue by meffect** [mrworf/plexupdate#172]
I can't tell if this offers any benefits over the official repo, any thoughts?

https://support.plex.tv/hc/en-us/articles/235974187-Enable-repository-updating-for-supported-Linux-server-distributions

**Comment by demonbane** [comment]
The two biggest differences are:

1. Plexupdate allows you to have fully automated upgrades anytime a new version is released
2. Plexupdate allows you to install beta releases if you have a PlexPass

If you don't have a PlexPass or don't want to use beta releases, and you prefer to manually do the upgrades (by running `apt-get update && apt-get upgrade`), the official solution is fine.

If you want to use beta releases or you want updates to be installed automatically as soon as they're available then Plexupdate is still very useful for that.

**Comment by meffect** [comment]
Hmm.. When you say beta, does beta = plexpass, or is there 3 versions? Does the plex repo not support plexpas versions?

**Comment by mrworf** [comment]
Beta refers to plex pass, and no, the repo versions don't support plex pass since there is no way to authenticate the user.

**Comment by meffect** [comment]
I see. Sounds like plexupdate is the way to go . Thanks
