### ISSUE TITLE
Why not making a Package Manager repository instead?

### ISSUE THREAD

**Issue by Skaronator** [mrworf/plexupdate#173]
Why not hosting a Repo with the Plex Pass releases if the Plex Inc. don't want to do it?

I prefer the package manager for updates and also there are reasons why automatic updates are bad. Even if Plex update seems fine and mostly stable.

**Comment by mrworf** [comment]
They would do it if they could limit distribution to PlexPass owners. Now, this is not possible so they can't do it. I don't disagree with your arguments, but I'm not going to place the PlexPass edition in a public apt repo. 

Then there's the issue with non-ubuntu based systems, meaning I would have to host RPM as well. Not to mention I'd have to host the files and incurr bandwidth costs :)

I seem to remember a discussion about this a while ago on Plex.tv but I can't find the link now.

**Comment by Skaronator** [comment]
Thanks for the quick response.

Only wondering why they are not forcing account login on Plex Pass releases and then just check if the account have a valid Plex Pass.

**Comment by Skaronator** [comment]
Did you ever tried to install the Plex Pass release with a non Plex Pass account?

**Comment by mrworf** [comment]
I think that's part of the issue, PlexPass editions are usually early releases with more functionality which they don't want everyone to test (imaging crashing all plex instances). People using PlexPass editions have defacto agreed that there might be some bumps in the road while the public editions are supposed to be more stable. It's like a stable (public) and unstable (plexpass) track :)

**Comment by mrworf** [comment]
Also, PlexPass editions don't require plexpass login, just regular I believe
