### ISSUE TITLE
How to update plexupdate script & at what hour the script check for autoupdate ?

### ISSUE THREAD

**Issue by Marbellasaad** [mrworf/plexupdate#174]
Hello,all is in the title,i see you have done an update to only use token,but how can i update to this ? And at what hour the script check for plex updates ? And if i enable this option : https://puu.sh/uxNIg/c7c948fb63.png to when the script will report the update time ? Can i check if he correctly detect my plex server ? 

 Thanks you !

**Comment by mrworf** [comment]
The token is used automatically if it can be detected, if it cannot find it and is forced to resort to email and password (and they are provided) you should get a warning.  If you installed plexupdate via the installer and allowed it to automatically update, then you'll get this feature and unless there's an issue, you should get token usage by default.

Regarding detection of plex server, you can always run plexupdate.sh manually from the command line to test it out, it will report if it cannot talk to your server. 

The cronjob runs the same time as anything else runs on the cron.daily schedule (see https://serverfault.com/questions/135906/when-does-cron-daily-run/422634 )

**Comment by demonbane** [comment]
The time the update runs depends on which distro and version you're running.

If you're using a recent version of Ubuntu or CentOS, you probably have anacron installed, so you can check either `/etc/cron.d/anacron` or `/etc/anacron`. If neither of those exist, then you can just run `grep daily /etc/crontab` as root. Keep in mind that for both of those, the minutes come first and then the hours. So mine says `25 6` for example, which means 6:25 am.

**Comment by Marbellasaad** [comment]
Thanks alot !

**Comment by Ardakilic** [comment]
For me (Debian Jessie), the script is located at

`/etc/cron.daily/plexupdate`, which is a link to `/opt/plexupdate/extras/cronwrapper` which is the actual code that updates.

So I believe is that we can disable the cron from the installer.sh and run the cronwrapper script any time with a custom cron code.
