### ISSUE TITLE
Update failures

### ISSUE THREAD

**Issue by brooks-bridges** [mrworf/plexupdate#175]
This is from a fresh install using the wget installer.sh method

_Auto-updating...
Auto-merging extras/installer.sh
CONFLICT (content): Merge conflict in extras/installer.sh
Auto-merging plexupdate.sh
CONFLICT (content): Merge conflict in plexupdate.sh
Automatic merge failed; fix conflicts and then commit the result.
ERROR: Unable to update git, try running "git pull" manually to see what is wrong
[root@server plexupdate]# git pull
U       extras/installer.sh
U       plexupdate.sh
Pull is not possible because you have unmerged files.
Please, fix them up in the work tree, and then use 'git add/rm <file>'
as appropriate to mark resolution, or use 'git commit -a'.
[root@server plexupdate]#_

**Comment by demonbane** [comment]
I just tested this on a clean machine and I couldn't replicate it.

Did that machine have plexupdate installed on it at any point in the past? Did you get any errors during the install process?

The first thing I'd try is to completely remove the plexupdate install directory and try it again. For example, if you had plexupdate installed at `/opt/plexupdate` you'd do `sudo rm -rf /opt/plexupdate`.

**Comment by brooks-bridges** [comment]
I did have it installed previously and it was throwing that error, so I did remove the plexupdate directory and re-ran the installer.  Everything worked as expected during the install, but then it still throws that error.

**Comment by brooks-bridges** [comment]
Here's doing it again:

_[root@server ~]# cd /opt/
[root@server opt]# rm -rf plexupdate/
[root@server opt]# bash -c "$(wget -qO - https://raw.githubusercontent.com/mrworf/plexupdate/master/extras/installer.sh)"

Directory to install into: /opt/plexupdate
'/opt/plexupdate' doesn't exist, attempting to create... done
Installing plexupdate into '/opt/plexupdate'... done

Do you want to install the latest PlexPass releases? (requires PlexPass account) [Y/n] 


Would you like to automatically install the latest release when it is downloaded? [Y/n] 


When using the auto-install option, would you like to check if the server is in use before upgrading? [Y/n] 

Plex Server IP/DNS name: 127.0.0.1
Plex Server Port: 32400

Writing configuration file '/etc/plexupdate.conf'... done

Would you like to set up automatic daily updates for Plex? [Y/n] n

Configuration complete. Would you like to run plexupdate with these settings now? [Y/n] y
Auto-updating...
Auto-merging extras/installer.sh
CONFLICT (content): Merge conflict in extras/installer.sh
Auto-merging plexupdate.sh
CONFLICT (content): Merge conflict in plexupdate.sh
Automatic merge failed; fix conflicts and then commit the result.
ERROR: Unable to update git, try running "git pull" manually to see what is wrong
[root@server opt]#_

**Comment by mrworf** [comment]
Do you have a .plexupdate in your home directory? If so, delete that, also remove the /etc/plexupdate.conf and finally remove the plexupdate folder and try installer again. 

If installer fails again, please run 'git diff' in the plexupdate folder and provide the output. 

Thanks ☺️

⁣Sent from TypeApp ​

**Comment by brooks-bridges** [comment]
no ~/.plexupdate file, removed /etc/plexupdate.conf, reinstalled again and having the same issue.  Here's the diff:

[root@server plexupdate]# git diff      
diff --cc extras/installer.sh
index ee5194a,8ddc6f2..0000000
--- a/extras/installer.sh
+++ b/extras/installer.sh
@@@ -13,7 -12,7 +13,11 @@@ AUTOUPDATE=ye
  PUBLIC=
  
  # variables to save in config
++<<<<<<< HEAD
 +CONFIGVARS="AUTOINSTALL AUTODELETE DOWNLOADDIR TOKEN FORCE FORCEALL PUBLIC AUTOSTART AUTOUPDATE PLEXSERVER PLEXPORT CHECKUPDATE NOTIFY"
++=======
+ CONFIGVARS="AUTOINSTALL AUTODELETE DOWNLOADDIR EMAIL PASS FORCE FORCEALL PUBLIC AUTOSTART AUTOUPDATE PLEXSERVER PLEXPORT CHECKUPDATE NOTIFY"
++>>>>>>> FETCH_HEAD
  CRONVARS="CONF SCRIPT LOGGING"
  
  install() {
diff --cc plexupdate.sh
index c49cfcf,8f994ac..0000000
--- a/plexupdate.sh
+++ b/plexupdate.sh
@@@ -13,7 -24,6 +13,10 @@@
  #         3 if page layout has changed.
  #         4 if download fails
  #         6 if update was deferred due to usage
++<<<<<<< HEAD
 +#         7 if update is available (requires --check-update)
++=======
++>>>>>>> FETCH_HEAD
  #        10 if new file was downloaded/installed (requires --notify-success)
  #       255 configuration is invalid
  #
@@@ -57,13 -68,49 +60,16 @@@ SHOWPROGRESS=n
  WGETOPTIONS=""        # extra options for wget. Used for progress bar.
  CHECKUPDATE=yes
  NOTIFY=no
++<<<<<<< HEAD
 +CHECKONLY=no
++=======
++>>>>>>> FETCH_HEAD
  
 -# Default options for package managers, override if needed
 -REDHAT_INSTALL="dnf -y install"
 -DEBIAN_INSTALL="dpkg -i"
 -DISTRO_INSTALL=""
 -
 -# Current pages we need - Do not change unless Plex.tv changes again
 -URL_LOGIN='https://plex.tv/users/sign_in.json'
 -URL_DOWNLOAD='https://plex.tv/api/downloads/1.json?channel=plexpass'
 -URL_DOWNLOAD_PUBLIC='https://plex.tv/api/downloads/1.json'
 -
 -#URL for new version check
 -UPSTREAM_GIT_URL='https://raw.githubusercontent.com/mrworf/plexupdate/master/plexupdate.sh'
 -
 -#Branch to fetch updates from
 -BRANCHNAME="master"
 -
 -#Files "owned" by plexupdate, for autoupdate
 -PLEXUPDATE_FILES="plexupdate.sh extras/installer.sh extras/cronwrapper"
 -
 -FILE_POSTDATA=$(mktemp /tmp/plexupdate.postdata.XXXX)
 -FILE_RAW=$(mktemp /tmp/plexupdate.raw.XXXX)
 -FILE_FAILCAUSE=$(mktemp /tmp/plexupdate.failcause.XXXX)
 -FILE_KAKA=$(mktemp /tmp/plexupdate.kaka.XXXX)
  FILE_SHA=$(mktemp /tmp/plexupdate.sha.XXXX)
  FILE_WGETLOG=$(mktemp /tmp/plexupdate.wget.XXXX)
 -FILE_LOCAL=$(mktemp /tmp/plexupdate.local.XXXX)
 -FILE_REMOTE=$(mktemp /tmp/plexupdate.remote.XXXX)
 +SCRIPT_PATH="$(dirname "$0")"
  
  ######################################################################
 -# Functions for rest of script
 -
 -warn() {
 -      echo "WARNING: $@" >&1
 -}
 -
 -info() {
 -      echo "$@" >&1
 -}
 -
 -error() {
 -      echo "ERROR: $@" >&2
 -}
  
  usage() {
        echo "Usage: $(basename $0) [-acdfFhlpPqsuU] [<long options>]"
@@@ -84,22 -132,96 +90,108 @@@
        echo "    -v Show additional debug information"
        echo ""
        echo "    Long Argument Options:"
 +      echo "    --check-update Check for new version of plex only"
        echo "    --config <path/to/config/file> Configuration file to use"
        echo "    --dldir <path/to/download/dir> Download directory to use"
 -      echo "    --email <plex.tv email> Plex.TV email address"
 -      echo "    --pass <plex.tv password> Plex.TV password"
 -      echo "    --server <Plex server address> Address of Plex Server"
 +      echo "    --help This help"
 +      echo "    --notify-success Set exit code 10 if update is available/installed"
        echo "    --port <Plex server port> Port for Plex Server. Used with --server"
++<<<<<<< HEAD
 +      echo "    --server <Plex server address> Address of Plex Server"
 +      echo "    --token Manually specify the token to use to download Plex Pass releases"
++=======
+       echo "    --notify-success Set exit code 10 if update is available/installed"
++>>>>>>> FETCH_HEAD
        echo ""
        exit 0
  }
  
++<<<<<<< HEAD
 +if ! source "${SCRIPT_PATH}/plexupdate-core"; then
 +      echo "ERROR: plexupdate-core can't be found. Please redownload plexupdate and try again." >2
 +      exit 1
 +fi
++=======
+ running() {
+       local DATA="$(wget --no-check-certificate -q -O - https://$1:$3/status/sessions?X-Plex-Token=$2)"
+       local RET=$?
+       if [ ${RET} -eq 0 ]; then
+               if [ -z "${DATA}" ]; then
+                       # Odd, but usually means noone is watching
+                       return 1
+               fi
+               echo "${DATA}" | grep -q '<MediaContainer size="0">'
+               if [ $? -eq 1 ]; then
+                       # not found means that one or more medias are being played
+                       return 0
+               fi
+               return 1
+       elif [ ${RET} -eq 4 ]; then
+               # No response, assume not running
+               return 1
+       else
+               # We do not know what this means...
+               warn "Unknown response (${RET}) from server >>>"
+               warn "${DATA}"
+               return 0
+       fi
+ }
+ 
+ trimQuotes() {
+       local __buffer=$1
+ 
+       # Remove leading single quote
+       __buffer=${__buffer#\'}
+       # Remove ending single quote
+       __buffer=${__buffer%\'}
+ 
+       echo $__buffer
+ }
+ 
+ # Useful functions
+ rawurlencode() {
+       local string="${1}"
+       local strlen=${#string}
+       local encoded=""
+ 
+       for (( pos=0 ; pos<strlen ; pos++ )); do
+               c=${string:$pos:1}
+               case "$c" in
+               [-_.~a-zA-Z0-9] ) o="${c}" ;;
+               * )               printf -v o '%%%02x' "'$c"
+               esac
+               encoded+="${o}"
+       done
+       echo "${encoded}"
+ }
+ 
+ keypair() {
+       local key="$( rawurlencode "$1" )"
+       local val="$( rawurlencode "$2" )"
+ 
+       echo "${key}=${val}"
+ }
+ 
+ getPlexServerToken() {
+       if [ -f /etc/default/plexmediaserver ]; then
+               source /etc/default/plexmediaserver
+       fi
+ 
+       # List possible locations to find Plex Server preference file
+       local VALIDPATHS=("${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}" "/var/lib/plexmediaserver/Library/Application Support/" "${HOME}/Library/Application Support/")
+       local PREFFILE="/Plex Media Server/Preferences.xml"
+ 
+       for I in "${VALIDPATHS[@]}" ; do
+               if [ ! -z "${I}" -a -f "${I}${PREFFILE}" ]; then
+                       sed -n 's/.*PlexOnlineToken="\([[:alnum:]]*\).*".*/\1/p' "${I}${PREFFILE}" 2>/dev/null
+                       if [ $? -ne 0 -a -z "${EMAIL}" -a -z "${PASS}" ]; then
+                               error "Do not have permission to read token from Plex Server preference file (${I}${PREFFILE})"
+                       fi
+                       exit 0
+               fi
+       done
+ }
++>>>>>>> FETCH_HEAD
  
  # Setup an exit handler so we cleanup
  cleanup() {
@@@ -109,7 -233,7 +201,11 @@@ trap cleanup EXI
  
  # Parse commandline
  ALLARGS=( "$@" )
++<<<<<<< HEAD
 +optstring="-o acCdfFhlpPqrSsuUv -l config:,dldir:,email:,pass:,server:,port:,token:,notify-success,check-update,help"
++=======
+ optstring="-o acCdfFhlpPqrSsuUv -l config:,dldir:,email:,pass:,server:,port:,notify-success"
++>>>>>>> FETCH_HEAD
  GETOPTRES=$(getopt $optstring -- "$@")
  if [ $? -eq 1 ]; then
        exit 1
@@@ -163,16 -287,13 +259,18 @@@ d
  
                (--config) shift;; #gobble up the paramater and silently continue parsing
                (--dldir) shift; DOWNLOADDIR=$(trimQuotes ${1});;
 -              (--email) shift; EMAIL=$(trimQuotes ${1});;
 -              (--pass) shift; PASS=$(trimQuotes ${1});;
 +              (--email) shift; warn "EMAIL is deprecated. Use TOKEN instead."; EMAIL=$(trimQuotes ${1});;
 +              (--pass) shift; warn "PASS is deprecated. Use TOKEN instead."; PASS=$(trimQuotes ${1});;
                (--server) shift; PLEXSERVER=$(trimQuotes ${1});;
                (--port) shift; PLEXPORT=$(trimQuotes ${1});;
 +              (--token) shift; TOKEN=$(trimQuotes ${1});;
 +              (--help) usage;;
 +
 +              (--notify-success) NOTIFY=yes;;
 +              (--check-update) CHECKONLY=yes;;
  
+               (--notify-success) NOTIFY=yes;;
+ 
                (--) ;;
                (-*) error "Unrecognized option $1"; usage; exit 1;;
                (*)  break;;
@@@ -439,16 -601,32 +537,44 @@@ if [[ $FILENAME == *$INSTALLED_VERSION
        exit 0
  fi
  
++<<<<<<< HEAD
 +if [ -f "${DOWNLOADDIR}/${FILENAME}" -a "${FORCE}" != "yes" ]; then
 +      if sha1sum --status -c "${FILE_SHA}"; then
 +              info "File already exists (${FILENAME}), won't download."
 +              if [ "${AUTOINSTALL}" != "yes" ]; then
 +                      exit 0
++=======
+ if [ -f "${DOWNLOADDIR}/${FILENAME}" ]; then
+       if [ "${FORCE}" != "yes" -a "${FORCEALL}" != "yes" ]; then
+               sha1sum --status -c "${FILE_SHA}"
+               if [ $? -eq 0 ]; then
+                       info "File already exists (${FILENAME}), won't download."
+                       if [ "${AUTOINSTALL}" != "yes" ]; then
+                               exit 0
+                       fi
+                       SKIP_DOWNLOAD="yes"
+               else
+                       info "File exists but fails checksum. Redownloading."
+                       SKIP_DOWNLOAD="no"
++>>>>>>> FETCH_HEAD
                fi
 -      elif [ "${FORCEALL}" == "yes" ]; then
 -              info "Note! File exists, but asked to overwrite with new copy"
 +              SKIP_DOWNLOAD="yes"
        else
++<<<<<<< HEAD
 +              info "File exists but fails checksum. Redownloading."
 +              SKIP_DOWNLOAD="no"
++=======
+               sha1sum --status -c "${FILE_SHA}"
+               if [ $? -ne 0 ]; then
+                       info "File exists but fails checksum. Redownloading."
+               else
+                       info "File exists and checksum passes, won't redownload."
+                       if [ "${AUTOINSTALL}" != "yes" ]; then
+                               exit 0
+                       fi
+                       SKIP_DOWNLOAD="yes"
+               fi
++>>>>>>> FETCH_HEAD
        fi
  fi
  
[root@server plexupdate]#

**Comment by mrworf** [comment]
Please run `git config --list | grep crlf` and post the output

**Comment by brooks-bridges** [comment]
no output

[root@server plexupdate]# git config --list | grep crlf
[root@server plexupdate]#

**Comment by brooks-bridges** [comment]
Here's the full config since it's not very big:


[root@server plexupdate]# git config --list
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/mrworf/plexupdate
branch.master.remote=origin
branch.master.merge=refs/heads/master
[root@server plexupdate]#

**Comment by mrworf** [comment]
can you also do a `git show` so we get the last commit on your git repo?

**Comment by demonbane** [comment]
Ok, try running this from /opt (you're going to get a few errors along the way which is ok)

```bash
rm -rvf plexupdate
rm -v ~/.plexupdate /etc/plexupdate.conf
ls -alhd plexupdate
git clone git://github.com/mrworf/plexupdate
cd plexupdate
git status
extras/installer.sh
```

At the end of the installer, answer NO to whether or not you want it to run plexupdate for you, then run:

```
git status
git diff
./plexupdate.sh
```

and paste all of the output (from the first `rm` to the end) into a [gist](https://gist.github.com) and include the link in your response.

**Comment by brooks-bridges** [comment]
https://gist.github.com/brooks-bridges/aa2a0426bc3b2ad48b600e19cd4802de

**Comment by mrworf** [comment]
Thanks, please run `git show` as well, it will tell us which was the latest commit on that git repo you have.

**Comment by brooks-bridges** [comment]
Here's the git show, sorry... missed your comment the first time

https://gist.github.com/brooks-bridges/cd3cd4e87b7ab93b309deee219102978

**Comment by mrworf** [comment]
What linux distro and hardware are you running? If you email github@sensenet.nu I'll invite you to our slack channel if you want

**Comment by brooks-bridges** [comment]
CentOS 6.8, Dell Optiplex 7010

The script was working perfectly fine until I noticed recently that it hadn't applied the latest update and went to see why

I'm actually getting ready to head to bed in a few, but I'll send you an email and we can revisit this tomorrow if you want

**Comment by mrworf** [comment]
sure, I'd love to get to the bottom of this :)

**Comment by mrworf** [comment]
Fixed with latest commit
