### ISSUE TITLE
REQUEST: Current Plex release version number sent to flat file

### ISSUE THREAD

**Issue by traxtar3** [mrworf/plexupdate#178]
To help with system monitoring for multiple servers, request the following:
Add in line 16
REL_NUMBER=

Add in line 399 (line after after FILENAME="$(basename 2>/dev/null ${DOWNLOAD})")
echo ${FILENAME}| sed 's/plexmediaserver_//' | sed 's/_amd64.deb//' > REL_NUMBER

REL_NUMBER file location could then be set in the plexupdate.conf file and version number could be re-directed to a flat file for read-in for different program (mine is conky for situational awareness)

I am sure there is a better way to cut out the 'amd64' bit for those using non-Debian architecture, but I'd love to see it.

Great work on the code btw, very handy.

**Comment by demonbane** [comment]
If you're just trying to get the most current release version, you can do something like this:

```
$ plexupdate.sh -r | tail -n1 | cut -d/ -f5 
1.5.1.3520-ed60c70d6
```

If you're specifically wanting that exposed inside of plexupdate, it would be helpful to tell us what you're planning so we can see if there's a better way.

Are you using plexupdate as part of another project? Or do you just want to have an easy way to get the most recent release number for something else?

**Comment by traxtar3** [comment]
Short story long, I'm using plexupdate as part of a different project.
I've got a few different servers that ping back hourly with their version
number. I'd like to be able to use plexupdate to print the version number
to a flat file in order to compare the two using a sysmon program. If they
differ, it puts up a warning to my main console to go manually update the
server. It's more of a failover in case plexupdate doesn't work for some
reason. I thonk since you incoperated the auto-token, it's an in-issue.
The reason I was using plexupdate was your use of tokens and enabling the
most recent non-public releases.
i'd prefer not to use what you put below because I'd have to do it as root
(I used the auto-install) and I'd like to pull the most recent release
number via cronjob. I have not looked at changing the permissions of the
script and/or having a different copy somewhere else that does this. I
think I will just do that and use what you have below. Will it work
properly (token, no git error, etc.) if it's copied to an outside folder?

On a different topic, have you thought about having this script run as
'user' instead of root?
You could invoke zenity with a "would you like to install new update" and
then invoke root using gksu when a new version has been downloaded.

Some are hesitant about scripts running as root

For most users, your application is spot on.

Thanks for the quick reply!

**Comment by demonbane** [comment]
As long the user you're running as has access to the plexupdate directory and your Plex folder (usually `/var/lib/plexmediaserver`, just so it can retrieve the token) it will run just fine as a non-privileged user. If you installed in the default `/opt/plexupdate` directory, non-privileged users should already have access to it, so you don't need to install it a second time.

We only run plexupdate as root as if you want automatic updates since root permissions are needed for that. If you just want plexupdate to tell you when a new version is available you don't have to run as root at all for that (though you'll just need to set up the cron job to run as a different user since the install script only knows how to install it for root right now).

**Comment by mrworf** [comment]
Actually, if you run the tool with `--check-update` it will check and return 0 if no new version exists or 7 if there is a newer version available.

If you install the script as non-cron you can add this test to your monitoring script and call it a day 😄

**Comment by mrworf** [comment]
I'm closing this issue. Please reopen if our suggestions didn't work
