### ISSUE TITLE
Support for Raspbian Jessie and Raspberry Pi

### ISSUE THREAD

**Issue by rowdya22** [mrworf/plexupdate#179]
I installed Plex on my Pi server and its running Jessie. I was hoping there was a distro work around or something I could do for Debian/Raspbian.

This is an awesome script and I cant wait to be able to use it!

**Comment by mrworf** [comment]
Hi, unfortunately, this is all up to the Plex folks, all my script will do is download the desired version of Plex Media Server. And unfortunately, they don't have any ARM version for Ubuntu available through it.

You might be able to download the netgear version and see if you can simply copy the raw contents of the debian package into the designated locations in Ubuntu, but I think that might be more trouble than it's worth to be honest.
