### ISSUE TITLE
Update failed with latest update (0.9.2.11.1406-8403350)

### ISSUE THREAD

**Issue by bcin** [mrworf/plexupdate#18]
I tried the script on both of my Ubuntu boxes this evening.  Note: Script worked fine last upgrade. 

I checked GIT for an update, then ran the script this evening. (although in briefly looking at the code, it's got an auto-updater now?)

All it seemed to do is download the upgrade file, but didn't go any further. No error message, until I thought I'd made a mistake and tried it again. Then it was kind of upset that the file to download was already there. :)

**Comment by AltonV** [comment]
Did you run it with the "-a" switch?
It will only download without it

**Comment by mrworf** [comment]
Do you have the output as well as what options you gave the script?

**Comment by bcin** [comment]
Sorry, been away. Please close this bug report. I had not noticed that
there were new command line switches. Last time I used it I just invoked it
and it "just ran"

Now I'll need "sudo" and -a it looks like.

**Comment by mrworf** [comment]
You might have been root before. But I'm glad it worked out. Closing the issue.

**Comment by bcin** [comment]
What does one do if you screw up the switches, it downloads it, but doesn't perform the update? However you want to install it anyways? I seem to have to delete the downloaded file and do it over again. It would be nice if there was a switch (or documented) or test to see if the file is already downloaded and continue with the install. (Yes, I know you could just perform a package install, but it would be nice for those that are just plodding through that it could be done.)

**Comment by mrworf** [comment]
Just re-run the script with -a as root and it will automatically detect that the file exists and skip and just install instead.

**Comment by mrworf** [comment]
(just tried it to be sure :D)
