### ISSUE TITLE
Notify on Update

### ISSUE THREAD

**Issue by rustymyers** [mrworf/plexupdate#180]
Hello, I'm interested in receiving notifications of updates through slack. I've added this to my own server, but I'm unable to update the plexupdate script in the future due to the changes. Is this something you'd be interested in adding to the script?

**Comment by mrworf** [comment]
Actually, if you run the script with the option `--check-update` the tool will return exit code 7 if there is an update available. And using https://gist.github.com/dopiaza/6449505 you should be able to do this:

```
#!/bin/bash

plexupdate.sh --check-update
if [ $? -eq 7 ]; then
  slackpost "https://someurl/" "plexupdate" "There's a new version available of Plex Media Server"
fi
```
In this scenario, you'd install plexupdate and set it to NOT automatically install/check updates to Plex and then add this script as a cronjob instead (with the correct paths and URLs)

**Comment by rustymyers** [comment]
Ok, thanks for the suggestion.
