### ISSUE TITLE
Need to patch user PMS is running as

### ISSUE THREAD

**Issue by Stinky78** [mrworf/plexupdate#181]
Hi there,

i have PMS running in OpenVZ and due to some bind-mount stuff, i need to run PMS as root user. So i have to patch several files so the service is started as user root.

But these files are always overwritten with new updates and when plexupdate ran and started PMS again, its running as user plex and does not work permission-wise.

The patches i do via:

sed -i -e '/User=/ s/=.*/=root/' /lib/systemd/system/plexmediaserver.service
sed -i -e '/Group=/ s/=.*/=root/' /lib/systemd/system/plexmediaserver.service
sed -i -e '/PLEX_MEDIA_SERVER_USER=/ s/=.*/=root/' /etc/default/plexmediaserver
systemctl daemon-reload

I tried to patch plexupdate so this is done during the update process and when it starts the service it is running as root ... but it doesnt work and i dont know where i could/should put this into the plexupdate.sh.

It would be amazing if plexupdate supports this directly so i would be able to still be able to autoupdate plexupdate itself with new versions without having it to be patched again.

Can someone help? plexupdate ist amazing and i really would like to use it. :(

bye
Stinky

**Comment by mrworf** [comment]
Well, what you'd want to do is add an else statement at https://github.com/mrworf/plexupdate/blob/master/plexupdate.sh#L492 so that if the install is successful, you'll patch the necessary files. At this point, you're root so you have full access.

So what you want is this:
```
else
  sed -i -e '/User=/ s/=./=root/' /lib/systemd/system/plexmediaserver.service
  sed -i -e '/Group=/ s/=./=root/' /lib/systemd/system/plexmediaserver.service
  sed -i -e '/PLEX_MEDIA_SERVER_USER=/ s/=.*/=root/' /etc/default/plexmediaserver
  systemctl daemon-reload
fi
```
But this will block plexupdate from auto-updating at this point. 

What you need is a POSTINSTALL-HOOK feature, which is trivial to implement (from my end) which would allow you to execute a command after install and in your case it would be another script which patches plex.

Let me see if I can't get that done later today (on PST time, so in about 12hrs or so).

**Comment by demonbane** [comment]
You guys are way over-complicating this. :) systemd has a built in overrides feature for exactly this purpose. Just run `systemctl edit plexmediaserver` as root and add this to the blank file that it opens for you:

```
[Service]
User=root
Group=root
```

Editing `/etc/defaults/plexmediaserver` isn't necessary since the systemd unit doesn't use that file anymore anyway.

**Comment by demonbane** [comment]
(p.s. since this is an override, it will persist across updates, so you don't have to run it every time you update. You just run it once and you're done.)

**Comment by mrworf** [comment]
@Stinky78 if this solves your issue, feel free to close this thread.

**Comment by Stinky78** [comment]
Hey guys, thank you. In Debian 8 there doesnt seem to be an "systemctl edit" ... at least it tells me:

`root@plex:~# systemctl edit plexmediaserver
Unknown operation 'edit'.`

Otherwise, yeah, this would fix it. Am i forgetting something?

**Comment by Stinky78** [comment]
And the /lib/systemd/system/plexmediaserver.service is the file i need to patch every time plexmediaserver is updated. Plex seems to update this file every time and there seems no override somehow?!

**Comment by demonbane** [comment]
If possible, I'd suggest [enabling backports](https://backports.debian.org/Instructions/#index2h2) for Debian Jessie and getting the updated version of systemd. You're currently at release 215 and this will get you up to 230 which will have the `edit` verb added.

If that's not an option for you, you can still do it manually, it just requires a couple of extra steps. You'll first need to create a drop-in directory in `/etc/systemd/system/plexmediaserver.service.d`, and then create a file inside that directory called `override.conf`. You can then paste the bit I provided above into that file.

Once that's done, just run `systemctl daemon-reload` followed by `systemctl restart plexmediaserver` and you should be all set.

**Comment by demonbane** [comment]
>And the /lib/systemd/system/plexmediaserver.service is the file i need to patch every time plexmediaserver is updated. Plex seems to update this file every time and there seems no override somehow?!

The files in `/lib/systemd/` are the "package configuration". These are the files that are provided by the package and should never be modified directly. If a **vendor** needs to make specific changes (i.e. Debian), those go into the vendor-specific location in `/usr/lib/systemd/`, and the **local** changes go into `/etc/systemd/`. At run-time, systemd starts by pulling in the package configuration in `/lib/systemd/`, it then pulls in any vendor-specific overrides from `/usr/lib/systemd/`, and then finally pulls in the changes in `/etc/systemd/`. The "latest" place where a parameter is defined wins for that particular parameter.

For example, let's say the package configuration specified:

```
[Service]
User=plex
Group=plex
```

And let's say that Ubuntu decided that all services should run under the group "wheel". In that case, they could drop in a vendor override in `/usr/lib/systemd/` with

```
[Service]
Group=wheel
```

If you then decide that you really want the service to run as the user "bob", without modifying the group, you could create an override in `/etc/systemd/` with

```
[Service]
User=bob
```

If you then run `systemctl show plexmediaserver -p User -p Group` you'll find that `User=bob` (from your configuration) and `Group=wheel` (from the vendor configuration), while all of the remaining settings are still as they were originally defined in the package configuration.

**Comment by Stinky78** [comment]
@demonbane You are amazing, thanks a bunch. To be honest I was unaware of the backports. I did as instructed, got systemd updated, edited and now everything works absolut perfectly. Thank you!!!

and @mrworf Thanks for this awesome script!
