### ISSUE TITLE
Error: Unable to retrieve the URL 

### ISSUE THREAD

**Issue by psun03** [mrworf/plexupdate#185]
I tried installing plexupdate. I followed you directions by typing in :

bash -c "$(wget -qO - https://raw.githubusercontent.com/mrworf/plexupdate/master/extras/installer.sh)"

It runs through a series of questions, but at the end I get this:
ERROR: Unable to retrieve the URL needed for download (Query DISTRO: ubuntu, BUILD: linux-ubuntu-armv7l)

Here is my distro info:

PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by mrworf** [comment]
Unfortunately, running Plex Media Server on Raspbian isn't officially supported as a Debian package so the tool cannot download a working package.
