### ISSUE TITLE
Does not download Plex Pass version with token specified

### ISSUE THREAD

**Issue by Gheez** [mrworf/plexupdate#187]
Right after I installed plexupdate with installer.sh it tried to update but didn't find the newest version.
I can see the new verison on https://www.plex.tv/downloads/ when logged in to plex.tv:

> Plex Media Server for Linux
>     1.7.2.3878-8088811b8
>     May 27, 2017

I tried running it manually and point to a config with a specified token:

> gheez@EPICPOWER:/opt/plexupdate$ sudo /opt/plexupdate/plexupdate.sh --config /etc/plexupdate.conf
> Retrieving list of available distributions
> Your OS reports the latest version of Plex (1.5.6.3790-4613ce077) is already installed. Use -f to force download.

> gheez@EPICPOWER:/opt/plexupdate$ cat /etc/plexupdate.conf
> AUTOINSTALL='yes'
> AUTODELETE='yes'
> DOWNLOADDIR='/tmp'
> PUBLIC='no'
> AUTOUPDATE='yes'
> PLEXSERVER='10.1.19.101'
> PLEXPORT='32400'
> NOTIFY='yes'
> TOKEN=\<secret\>

System information:

> gheez@EPICPOWER:\~$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.2 LTS
> Release:        16.04
> Codename:       xenial
> gheez@EPICPOWER:~$ uname -r
> 4.4.0-78-generic

**Comment by Gheez** [comment]
Tried reinstalling it:

> gheez@EPICPOWER:~$ /opt/plexupdate/extras/installer.sh
> 
> This script needs to install files in system locations and will ask for sudo/root permissions now
> 
> Found plexupdate.sh in '/opt/plexupdate', using that as your install path
> 
> Do you want to install the latest PlexPass releases? (requires PlexPass account) [Y/n] y
> 
> Would you like to automatically install the latest release when it is downloaded? [Y/n] y
> 
> When using the auto-install option, would you like to check if the server is in use before upgrading? [Y/n] y
> Plex Server IP/DNS name: 10.1.19.101
> Plex Server Port: 32400
> 
> Writing configuration file '/etc/plexupdate.conf'... done
> 
> Would you like to set up automatic daily updates for Plex? [Y/n] y
> 
> Do you want to log the daily update runs to syslog so you can examine the output later? [Y/n] y
> 
> Should cron send you an email if an update is available/installed? [Y/n] y
> 
> Writing configuration file '/etc/plexupdate.conf'... done
> 
> Writing configuration file '/etc/plexupdate.cron.conf'... done
> 
> Installing daily cron job... done
> 
> Configuration complete. Would you like to run plexupdate with these settings now? [Y/n] y
> Retrieving list of available distributions
> Your OS reports the latest version of Plex (1.5.6.3790-4613ce077) is already installed. Use -f to force download.

After reinstalling it, it seems like it removed the line with TOKEN= in the config:

> gheez@EPICPOWER:\~$ cat /etc/plexupdate.conf
> AUTOINSTALL='yes'
> AUTODELETE='yes'
> DOWNLOADDIR='/tmp'
> PUBLIC='no'
> AUTOUPDATE='yes'
> PLEXSERVER='10.1.19.101'
> PLEXPORT='32400'
> NOTIFY='yes'

**Comment by mscreations** [comment]
Try running it with the verbose option (-v) and report what it says. You're definitely getting the public version rather than plexpass, so it is having a hard time getting a token somewhere.

**Comment by Gheez** [comment]
Using the verbose option didn't give any error information, and I realized I read plexupdate will read the credentials from the Plex Server preferences.xml file, I removed it and re-run the script. It asked for my email and password, and it found the new plex server version.

Before I did, I checked the Preferences.xml file for a token, I found one and tried in manually in plexupdate but it didn't find the new version.

It seems you should not try to use token specified in Preferences.xml since it might be a deprecated parameter or just not often updated. I just got a new token with your provided method and added it manually to plexupdate.conf.

Working like a charm.
