### ISSUE TITLE
Using ~ in quoted DOWNLOADDIR causes download to fail

### ISSUE THREAD

**Issue by josteink** [mrworf/plexupdate#19]
This is an error not caused by the script itself, but by how wget and/or the shell treats this value.

The typical error an end-user sees is this:

```` bash
$ ./plexupdate.sh   
Authenticating...OK
Finding download URL for 64-bit...OK
 !! Download failed with code 1, "~/.plexupdates/plexmediaserver_0.9.12.12.1459-49fe448_amd64.deb: No such file or directory"
````

This can be reproduced independently from the script itself:

````bash
# quoted with ~, fails
$ wget -O "~/.plexdownloads/test1.deb" 
https://downloads.plex.tv/plex-media-server/0.9.12.11.1406-8403350/plexmediaserver_0.9.12.11.1406-8403350_amd64.deb

# unquoted with ~, succeeds
$ wget -O ~/.plexdownloads/test2.deb 
https://downloads.plex.tv/plex-media-server/0.9.12.11.1406-8403350/plexmediaserver_0.9.12.11.1406-8403350_amd64.deb

# expanded ~ with quotes, succeeds
$ wget -O "/home/user/.plexdownloads/test3.deb" 
https://downloads.plex.tv/plex-media-server/0.9.12.11.1406-8403350/plexmediaserver_0.9.12.11.1406-8403350_amd64.deb

````

Since we really want to be quoting our strings, the remaining option is to expand the DOWNLOADDIR-variable ourselves, and for now that is also a reasonable manual workaround, but it should be documented.

For the future, the script should be able to apply this workaround itself.

**Comment by josteink** [comment]
Actually, thinking this smelled a bit fishy, I looked one inch deeper and checked my settings.

This only happens if you use quotes when you set your `DOWNLOADDIR` variable (in `plexupdate.sh` or in `.plexupdate`), as in the example below:

````bash
DOWNLOADDIR="~/.plexupdates"
````

If you don't use quotes, as below, it all works fine.

````bash
DOWNLOADDIR=~/.plexupdates
````

Warnings about this should probably be written down or documented somewhere. It's an easy mistake to make :)

**Comment by mrworf** [comment]
Updated the script, either version should work fine now. Please reopen issue if it still gives you issues.

**Comment by josteink** [comment]
I tried fooling around with a `pushd` and `popd` based solution, because I wanted to send in a PR, but ran into the same problem I initially had with  `wget`. Didn't know about `eval` before though. 

Thanks for the quick feedback, quick fix and for teaching me a new trick :)

**Comment by mrworf** [comment]
Np :)
