### ISSUE TITLE
Adding an option.

### ISSUE THREAD

**Issue by triney37** [mrworf/plexupdate#191]
I'm very new to this stuff more dangerous than anything. But if I wanted to add a line that runs a curl script when plexupdate has updated plex successful where would I add it at, or it could just tell it to run another script.

**Comment by mrworf** [comment]
You'd have a script execute plexupdate and check the result code. If successful, you run your curl command.

**Comment by triney37** [comment]
I ended up adding a line to the bottom of your plexupdate.sh where the
notifications is sent if successful to where it now runs a script. Now I
get a text through ifttt when it updates plex with the version.

On Wed, Jun 21, 2017 at 12:27 PM, Henric Andersson <notifications@github.com
