### ISSUE TITLE
ERROR: Failed to install update.

### ISSUE THREAD

**Issue by cronner** [mrworf/plexupdate#192]
Keeps getting:

ERROR: Failed to install update. Command 'dpkg -i /tmp/plexmediaserver_1.7.5.4035-313f93718_amd64.deb' returned error code 1

tried ubuntu 16.04 fresh install, debian 9.0 fresh install same result

**Comment by demonbane** [comment]
Are you running plexupdate from the command-line or from a cron job? And is there any other output produced before the ERROR line?

**Comment by albertrdixon** [comment]
Ran into this as well running plexupdate inside a Debian 8 based Docker container. Appears to be an issue in the post-install, so perhaps just a plex issue, and not plexupdate per se. Here's the output:

```
Jul 01 18:25:17 media-server docker[4629]: Installing Plex PlexPass.............................................dpkg: error processing package plexmediaserver (--install):
Jul 01 18:25:17 media-server docker[4629]:  subprocess installed post-installation script returned error exit status 2
Jul 01 18:25:17 media-server docker[4629]: Errors were encountered while processing:
Jul 01 18:25:17 media-server docker[4629]:  plexmediaserver
Jul 01 18:25:17 media-server docker[4629]: ERROR: Failed to install update. Command 'dpkg -i /tmp/plexmediaserver_1.7.5.4035-313f93718_amd64.deb' returned error code 1
```

**Comment by albertrdixon** [comment]
Ok, so it is choking for me here (might just be running it in a container, but I bet it is choking for @cronner there too):

```
root@plex:/usr/lib/plexmediaserver# dpkg --configure plexmediaserver
Setting up plexmediaserver (1.7.5.4035-313f93718) ...
+ action=configure
...
+ udevadm control --reload-rules
dpkg: error processing package plexmediaserver (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 plexmediaserver
```

So maybe nudge the plex folks to change that to just `udevadm trigger` (which reloads the rules anyways I think).

(works fine after commenting out the `udevadm control --reload`)
```
if [ -f /sbin/udevadm ]; then
  # udevadm control --reload-rules
  udevadm trigger
else
```

**Comment by cronner** [comment]
It's from a fresh install and with updates also with an old debian 8 install, running in a LXC container 

# dpkg --configure plexmediaserver
Setting up plexmediaserver (1.7.5.4035-313f93718) ...
dpkg: error processing package plexmediaserver (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 plexmediaserver

**Comment by cronner** [comment]
it's a Plex bug https://forums.plex.tv/discussion/277748/cant-install-plex-1-7-5-on-ubuntu-16-04

**Comment by gtwy** [comment]
It is a Plex issue. If you go to the above link posted by cronner, Plex fixed it in latest update.

However, the PlexUpdate script didn't grab the latest update. I had to install it manually to get it updating again.

**Comment by SGajewski** [comment]
I am still getting "ERROR: Failed to install update. Command 'dpkg -i /temp/plexmediaserver_1.7.6.4058-8fa494d15_amd64.deb' returned error code 1". Has anyone figured out a work-around? 

Full code:
```
Retrieving list of available distributions
Downloading release "plexmediaserver_1.7.6.4058-8fa494d15_amd64.deb"
/tmp/plexmediaserve 100%[===================>] 101.83M  10.3MB/s    in 9.5s
File downloaded
(Reading database ... 137084 files and directories currently installed.)
Preparing to unpack .../plexmediaserver_1.7.6.4058-8fa494d15_amd64.deb ...
Removed symlink /etc/systemd/system/multi-user.target.wants/plexmediaserver.serv   ice.
Unpacking plexmediaserver (1.7.6.4058-8fa494d15) over (1.7.6.4058-8fa494d15) ...
Setting up plexmediaserver (1.7.6.4058-8fa494d15) ...
Created symlink from /etc/systemd/system/multi-user.target.wants/plexmediaserver   .service to /lib/systemd/system/plexmediaserver.service.
Job for plexmediaserver.service failed because the control process exited with error code. See "systemctl status plexmediaserver.service" and "journalctl -xe" f   or details.
dpkg: error processing package plexmediaserver (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (229-4ubuntu19) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 plexmediaserver
```

**Comment by demonbane** [comment]
@SGajewski Did you ever get this sorted out? Are you still having the issue or did a later release of Plex fix it?

**Comment by SGajewski** [comment]
Alex,

Yes, it's all sorted out. It was a permission issue. I thought I closed out the forum post; sorry if I didn't.
