### ISSUE TITLE
Unable to retrieve the URL needed for download

### ISSUE THREAD

**Issue by fastkyle** [mrworf/plexupdate#193]
Hey,  I've been running this same build for over a month with no issues.  Recently I've noticed that Plex has not been updating for me.  I've checked that the downloads are available on plex.tv, which they are, and am completely stumped as to why this error is now popping up.  

```
$ sudo /opt/plexupdate/plexupdate.sh --config /opt/ProgramData/plexupdate/plexupdate.conf
Retrieving list of available distributions
ERROR: Unable to retrieve the URL needed for download (Query DISTRO: ubuntu, BUILD: linux-ubuntu-x86_64)
```

Any help would be greatly appreciated!

**Comment by fastkyle** [comment]
Some additional info:

Updates usually occur on a cronjob

Distro info:
`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial`

**Comment by demonbane** [comment]
I just went back through the code and I'm really stumped here. Even if there was a problem with your token or your username/password, you'd still at least get the public URL. The only thing that I can think of would be that you're maybe failing to resolve the DNS name correctly.

Just to make sure we've got all of our bases covered, please provide the output from the following (all run from inside your plexupdate directory, one at a time):

`git rev-parse HEAD`
`./plexupdate.sh -v --config /opt/ProgramData/plexupdate/plexupdate.conf`
`dig downloads.plex.tv 2>/dev/null || host downloads.plex.tv`

P.S. You can remove `USER` and `PASS` from your config if you'd like. We now use your Plex token by default.

**Comment by fastkyle** [comment]
Thanks for the user/pass tip.  Here's the output:

```
~/opt/plexupdate$ git rev-parse HEAD
483f9b06f7e17d742a04b0f5a74f42d8fbeb7486
```
```
~/opt/plexupdate$ sudo ./plexupdate.sh -v --config /opt/ProgramData/plexupdate/plexupdate.conf
Fetching token from Plex server
Retrieving list of available distributions
RELEASE=
DOWNLOAD=
CHECKSUM=
ERROR: Unable to retrieve the URL needed for download (Query DISTRO: ubuntu, BUILD: linux-ubuntu-x86_64)
```
```
~/opt/plexupdate$ dig downloads.plex.tv 2>/dev/null || host downloads.plex.tv

; <<>> DiG 9.10.3-P4-Ubuntu <<>> downloads.plex.tv
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33373
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;downloads.plex.tv.             IN      A

;; ANSWER SECTION:
downloads.plex.tv.      60      IN      CNAME   downloads.plex.tv.cdn.cloudflare.net.
downloads.plex.tv.cdn.cloudflare.net. 133 IN A  104.20.7.9
downloads.plex.tv.cdn.cloudflare.net. 133 IN A  104.20.6.9

;; Query time: 38 msec
;; SERVER: 209.222.18.222#53(209.222.18.222)
;; WHEN: Wed Jul 19 08:29:07 EDT 2017
;; MSG SIZE  rcvd: 128
```

**Comment by demonbane** [comment]
Well, that narrows it down at least. Let's try this:

`wget $(grep URL_DOWNLOAD= plexupdate-core | cut -f2 -d\') -SO -`

**Comment by fastkyle** [comment]
Ahh.  I recently installed openSSL to secure access to my Monit service.  This was a process that I was very unfamiliar with (and still is...).  Could this be the culprit?

```
~/opt/plexupdate$ sudo wget $(grep URL_DOWNLOAD= plexupdate-core | cut -f2 -d\') -SO -
--2017-07-19 09:02:57--  https://plex.tv/api/downloads/1.json?channel=plexpass
Resolving plex.tv (plex.tv)... 54.72.10.166, 52.48.156.83, 52.48.235.226, ...
Connecting to plex.tv (plex.tv)|54.72.10.166|:443... connected.
ERROR: cannot verify plex.tv's certificate, issued by ‘CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to plex.tv insecurely, use `--no-check-certificate'.
```

**Comment by demonbane** [comment]
If all you did was install OpenSSL it shouldn't have broken anything, but if you made any additional changes to your root certificates, that could have broken things.

Your root certificates are in the ca-certificates package so you can just try `sudo apt-get install --reinstall ca-certificates` and see if that fixes it.

**Comment by fastkyle** [comment]
This command fixed it.  Sorry to log an issue for PlexUpdate -- I guess I was in over my head w/ the certificate setup...

Thanks for your help!
