### ISSUE TITLE
Cannot update because the server is currently in use

### ISSUE THREAD

**Issue by adikari** [mrworf/plexupdate#198]
I am getting error when running plex update.

`ERROR: Server 127.0.0.1 is currently being used..`

I can confirm that the server is not in use. So I decided to debug what was happening. 

In line **479** of `plexupdate.sh`, It is checking if the server is currently running. 

`if running ${PLEXSERVER} ${TOKEN} ${PLEXPORT}`

In my case, the value of ${TOKEN} is empty. So when the `running` functions is called where its trying to build the url to check if the server is running the `$3` which is supposed to be port number is empty and `$2` which is supposed to be `TOKEN` has value of `PORT`. This leads to `wget` performing request in the url without the port number and returns invalid data.

I havent looked at the entire code yet to figure out what the value of ${TOKEN} should be in `plexupdate.sh`.  I think we could fix this by changing the ordering of parameters of the `running` function to be ${PLEXSERVER} ${PLEXPORT} ${TOKEN}. 

Let me know if my findings are correct. If you think the proposed solution should be ok then I am happy to create a PR with the fix.

**Comment by demonbane** [comment]
You're right about why it's failing, though I'm not sure if your proposed fix would work. At least on my server, a token is required to check the status even when checking localhost. So the `running` check would still fail, just for a different reason.

I think what we need to track down is why this check is happening in the first place if a token isn't available.

**Comment by adikari** [comment]
Yep you are right. I will look into this again when I have some extra time. For now I have disabled checking if server is active.

**Comment by mrworf** [comment]
@demonbane We should probably also enclose parameter calls like that with quotes which would at least allow the function to deal with blank parameters instead of sending too few

**Comment by mrworf** [comment]
@adikari Just out of curiousity, where is your plex media server installed and which user runs the cron script which updates your server?

**Comment by demonbane** [comment]
@mrworf Good catch. The call would still fail, but at least for the right reason (depending on which parameter is missing). PR incoming.

**Comment by demonbane** [comment]
This will just skip the activity check if TOKEN isn't available. If we find out in the future that there is some way to do activity checks without the token, we can handle that in a separate issue.

**Comment by adikari** [comment]
@mrworf The cron is running as root. Not sure what you mean by where is plex media server installed. If you mean the path its `/var/lib/plexmediaserver`.

**Comment by adikari** [comment]
@demonbane I can confirm that `getPlexToken` works. However where is `${TOKEN}` being set? My issue is that `${TOKEN}` is empty.
