### ISSUE TITLE
Readme issues

### ISSUE THREAD

**Issue by camjac251** [mrworf/plexupdate#20]
I tried following the guide and found a few issues. Everything is working now but it may help for those in the future who try installing it.

In 2. setting it up you have it set to email and pass, but in TL;DR, you have user and pass. User and pass wont work if the user has the only accept email option enabled.

Second thing, wget https://github.com/mrworf/plexupdate/blob/master/plexupdate.sh  downloads the html page, not the actual code.

https://raw.githubusercontent.com/mrworf/plexupdate/master/plexupdate.sh would be the right link instead.

**Comment by AltonV** [comment]
In tl;dr it says:
USER=<plex email account>

But I agree the wget link should be updated

**Comment by mrworf** [comment]
Ah, thanks :) That's what I get for doing nighttime updates. Will update asap

**Comment by mrworf** [comment]
Alright, now it's corrected. Thanks for letting me know.
