### ISSUE TITLE
Public edition downloads not working

### ISSUE THREAD

**Issue by brooss** [mrworf/plexupdate#201]
Since ab7f4052b1689f15529c906fedb894b1bd2ce3f3 it seems the -p (PUBLIC) option is no longer respected when running the script and the PlexPass edition is always downloaded.

**Comment by demonbane** [comment]
This isn't a change with plexupdate, it's just that the most current release from Plex is the same version for both. If you go to https://www.plex.tv/downloads/ you'll see that the Plex Pass release and the public release are both the same version at the moment.

**Comment by brooss** [comment]
Thank you for the reply. However the issue we're having isn't with the actual file downloaded, it's that plexupdate is now prompting for login credentials even with the -p flag or PUBLIC config specified.

**Comment by mrworf** [comment]
Do you have plexserver defined, that is, did you specify the server which runs plex? It will (currently) cause plexupdate to try and get a token for it even if you specify public=yes. So it's not trying to download plexpass version, just communicating with the server.

**Comment by brooss** [comment]
193f8f832a5 seems to fix this for our use case.
