### ISSUE TITLE
Problem with Download directory

### ISSUE THREAD

**Issue by xombiemp** [mrworf/plexupdate#21]
My .plexupdate file contains:
DOWNLOADDIR="/data/plexmediaserver/Library/Application Support/Plex Media Server"

When I try to run plexupdate I'm getting:
Error: Download directory does not exist or is not a directory

I noticed you committed a change recently for checking the download directory.  On line 136 you are doing eval pushd.  I tried this command by itself in the bash prompt with my directory and got this:
bash> eval pushd "/data/plexmediaserver/Library/Application Support/Plex Media Server"
-bash: pushd: /data/plexmediaserver/Library/Application: No such file or directory

I then tried the same command but without the eval part and it worked fine.  So I tried removing the eval command on line 136 so it just says pushd and the script ran fine for me.  Not sure exactly what is happening, but I think it has to do with spaces being in my path.  Why is the eval there and is it necessary?  The script only runs for me if it's not there.

**Comment by mrworf** [comment]
The reason I need eval was to deal with ~ in the path. But I'll find another way of dealing with it.

**Comment by xombiemp** [comment]
Looks like it's not a very easy problem to solve, but maybe a solution presented here would work: http://stackoverflow.com/questions/3963716/how-to-manually-expand-a-special-variable-ex-tilde-in-bash/27485157#27485157

**Comment by mrworf** [comment]
Found my own way which seems resilient to most issues, pushed to change, please give it a try. If it's still broken, reopen this issue. 

Thanks
