### ISSUE TITLE
ARMv7 64bit on Debian stretch

### ISSUE THREAD

**Issue by ivomarino** [mrworf/plexupdate#212]
Hi there, running PMS for ARMv7 64bit on Debian stretch here, repo:
`deb [arch=armhf] https://dev2day.de/pms/ stretch main`.

Was just wondering which `DISTRO` and `BUILD` to set from these:

```
root@LibreELEC:~# /opt/plexupdate/plexupdate.sh -l | grep -i arm
asustor      linux-armada-arm7              ARMv7
qnap         linux-annapurna-arm7           ARMv7-X31+/X31P/X31X/1635
qnap         linux-qnapx31-armv7            ARMv7-X31
readynas6    linux-annapurnatrans-arm7      ARM 6.x RN2xx
readynas6    linux-armada-arm7              ARM 6.x
seagate      linux-seagate-arm7             ARMv7
synology     linux-synology-armv7           ARMv7
wd-ex2100    linux-wd-armv7                 My Cloud EX2100
wd-ex2       linux-wd-armv7                 My Cloud EX2
wd-ex2ultra  linux-wd-armv7                 My Cloud EX2 Ultra
wd-ex4100    linux-wd-armv7                 My Cloud EX4100
wd-mirrg2    linux-wd-armv7                 My Cloud Mirror Gen2
wd-mirr      linux-wd-armv7                 My Cloud Mirror
```

PMS would like to download this version https://downloads.plex.tv/plex-media-server/1.9.6.4429-23901a099/PlexMediaServer-1.9.6.4429-23901a099-arm7.spk. Thanks for help.

**Comment by mrworf** [comment]
Since it's not an official release, plexupdate doesn't support it. The benefit with the one you referred to is that you most likely get it via regular updates and thus doesn't need plexupdate at all.

**Comment by ivomarino** [comment]
thanks @mrworf for feedback, yes this seems to be the best way for updates;)
