### ISSUE TITLE
plexupdate on debian armhf (rock64)

### ISSUE THREAD

**Issue by jata1** [mrworf/plexupdate#216]
Hi - i'm hoping someone can assist me with a config question...

plexupdate installed on my linux board - rock64 - running jessie. when I run plexupdate.sh it reports the following error:

ERROR: Unable to retrieve the URL needed for download (Query DISTRO: ubuntu, BUILD: linux-ubuntu-aarch64

I think the issue might be due to the  'aarch64' being returned by uname -m. The actual processor is armv8

what i need is the script to return the linux armhf (32bit) plexserver install...

Any ideas?

**Comment by elRadix** [comment]
@jata1 have a look here for arm pacakges, try those
let us know if it works

**Comment by mrworf** [comment]
You can override DISTRO and BUILD using the config. Let me know if it works
