### ISSUE TITLE
Domain User is unable to create the update folder

### ISSUE THREAD

**Issue by joeknock90** [mrworf/plexupdate#217]
I can work around this for now, but when running the install script with a domain user (using SSSD) the script is unable to run due to the space in Domain Users. 

I suppose you'd have to either get quotes into the users spot or escape the space in Domain\ Users. 

Let me know if you need help with this one, I have some ideas on how to get it work work.

**Comment by demonbane** [comment]
I think this is mostly likely due to using names for user/group instead of id's. @joeknock90 can you please test it to make sure it takes care of the problem for you?

To run the installer from my fork just use:
```sh
bash -c "$(wget -qO - https://raw.githubusercontent.com/demonbane/plexupdate/fix-217/extras/installer.sh)"
```
