### ISSUE TITLE
I already have a download file?

### ISSUE THREAD

**Issue by abbasmaheryar** [mrworf/plexupdate#218]
`Your OS reports the latest version of Plex (1.10.1.4602-f54242b6b) is already installed. Use -f to force download.`

This is what I am getting when running a plexupdate after it prompted me to after the installation. What do I have to do after here?

**Comment by demonbane** [comment]
@abbasmaheryar You don't need to do anything. That message is just telling you that you already had the latest version of Plex installed prior to installing plexupdate, so plexupdate has nothing to do right now. But the next time Plex is updated you'll be ready for it.

**Comment by abbasmaheryar** [comment]
Ah, I get it, thank you!
