### ISSUE TITLE
Your OS reports the latest version of Plex is already installed

### ISSUE THREAD

**Issue by checktravis** [mrworf/plexupdate#223]
Plex tells me there is a new version available, Version 1.12.0.4829

But this script says Your OS reports the latest version of Plex (1.11.3.4803-c40bba82e) is already installed.

I chose the plexpass option.

**Comment by demonbane** [comment]
Can you run plexupdate with the `-v` option and provide the output? It's most likely an issue with your Plex token, but we need to know where it's being pulled from first.

**Comment by demonbane** [comment]
@checktravis Are you still having this problem?

**Comment by checktravis** [comment]
Sorry for the delayed response, it seems to have updated on it's own.
