### ISSUE TITLE
Plexpass setting not checking plexpass (now called plexpass beta channel) releases

### ISSUE THREAD

**Issue by derekcentrico** [mrworf/plexupdate#225]
Essentially, plexpass members aren't getting anything but early access to new features through the plexpass beta channel these days.  As such, the script is not downloading the latest Plexpass.  For instance, it keeps saying I'm on the current release being 1.11.0.xxx. whereas 1.12.0.xxx is available as of February 28 for Plexpass folks via that beta channel.

My configuration is set to auto-install Plexpass releases for this script...

How can I take advantage of the Plexpass releases vs. being essentially stuck in public release situation?

**Comment by demonbane** [comment]
This is due to what appears to be a bug with the Plex API that recently started happening. Please follow #224 for details. Closing this as a duplicate.
