### ISSUE TITLE
Stuck at "Retrieving list of available distributions"

### ISSUE THREAD

**Issue by carnivorouz** [mrworf/plexupdate#241]
This seems to be a very recent change like maybe the URL is different, affecting the wget.  I re-ran the installer to make sure I wasn't just on an old build.
Not sure what else to include since it just gets stuck at the first part of the script.

**Comment by demonbane** [comment]
I just checked the URLs and everything still seems fine on my end at least. I ran it manually just now and it completes fine and I just had an update get installed this morning (1.13.3.5208-20455f518).

Try going to this URL from your browser:

https://plex.tv/api/downloads/1.json

That's the exact location we pull data from, so if it works through your browser it should work from the command line as well.

You can also see if one of the log files stuck around by looking in `/tmp`. The file will be named `/tmp/plexupdate.wget.<randomstring>`. It normally gets deleted after the script exits, but if it's still there it might give us some useful information.

You can also try running with `-v` just in case the error is happening after the download but before we do anything else. (there's a message that gets printed right after the first download completes when run with `-v`.)

**Comment by carnivorouz** [comment]
And found it finally.  I use this VPNBypassForLinux on the system that downloads media and at one point had also put it on the streaming system and it changed /etc/hosts.  The hardcoded value for plex.tv must have been just fine for the longest....until it wasn't ;)
Thanks for help

**Comment by demonbane** [comment]
Glad you got it figured out.
