### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by jwaltrip4** [mrworf/plexupdate#248]
It works after a fashion....

I am in Beta channel, and it is not updating from there...  Only Public...
I was under the impression that it defaulted to Beta...

**Comment by demonbane** [comment]
As long as you have a PlexPass account and are logged in with it, it should work just fine. However, there has been a problem on Plex's side for the last few days where their download page hasn't been updating with the latest release. (See [my comment](https://github.com/mrworf/plexupdate/issues/224#issuecomment-461665890) on #224)

As soon as they get the problems with their page sorted, plexupdate should find the new release and be able to install it for you with no problem. (assuming you're on a supported platform of course)

**Comment by plittlefield** [comment]
Ah, that explains mine not updating; thanks for the info and keep up the great work :-)

**Comment by demonbane** [comment]
I just reopened #224 so I'm going to go ahead and close this so we don't have duplicates. If you haven't commented in the other issue yet, just remember to subscribe to notifications for it if you want to know when it's been fixed.
