### ISSUE TITLE
Unable to retrieve the URL needed for download

### ISSUE THREAD

**Issue by cronner** [mrworf/plexupdate#249]
Just installed the script and I can't download plexmediaserver, using Ubuntu 18.04

```
./plexupdate.sh
Retrieving list of available distributions
ERROR: Unable to retrieve the URL needed for download (Query DISTRO: ubuntu, BUILD: linux-ubuntu-x86_64)
```

```
./plexupdate.sh -v
Fetching token from Plex server
Retrieving list of available distributions
RELEASE=
DOWNLOAD=
CHECKSUM=
ERROR: Unable to retrieve the URL needed for download (Query DISTRO: ubuntu, BUILD: linux-ubuntu-x86_64)
```

**Comment by demonbane** [comment]
This looks like it might be a connection issue of some sort. While we've been seeing some problems with the Plex download pages not updating, they still **have** the data, it's just old.

If you're using PlexPass, please try it one more time using the public channel (`plexupdate.sh -pv`), and if that doesn't work try running this command manually from the same machine:

```
wget 'https://plex.tv/api/downloads/1.json' -O -
```

That should return a wall of text ending with something that looks similar to this:

```
"checksum":"0ad39a9158c6dbf1b53306e2ee9dc5d9cde3720e"},{"label":"My Cloud Mirror Gen2","build":"linux-wd-armv7","distro":"wd-mirrg2","url":"https://downloads.plex.tv/plex-media-server/1.14.1.5488-cc260c476/WDMyCloudMirrorGen2_plexmediaserver_11415488-cc260c476.bin","checksum":"57108fe2a426372d6234e0513e50fc60a0a8724a"}]}}}
```

If you get something that looks more like HTML or anything else, paste it into a [gist](https://gist.github.com) and paste the link here.

**Comment by cronner** [comment]
public works:

Retrieving list of available distributions
Downloading release "plexmediaserver_1.14.1.5488-cc260c476_amd64.deb"

I could manually download 1.15 but it's gone again from their download site for me

**Comment by Scully66** [comment]
I am seeing the same issue. The Server is notifying me that the newest version is 1.15.0.659, But when I run the wget command above, the last version listed is the 1.14.1.5488.

This make me think they are only offering it through the manual download page... again..  Maybe they are just being slow at updating the distro page again.

**Comment by demonbane** [comment]
The 1.15 update not downloading is a separate issue that's being tracked in #224 (it's due to a problem on their end with the download page).

@cronner, can you try it with the PlexPass version one more time and see if it works now? It'll probably still tell you that there's no new version (because of the above-mentioned issue), but it shouldn't return an error. If it does, we'll have to do some more troubleshooting because that shouldn't happen. Any errors on the server side when doing a PlexPass check usually just cause it to fall back to public anyway, so getting an error of any kind there is definitely out of the ordinary.

**Comment by demonbane** [comment]
@cronner are you still having this problem or can we close out the issue?

**Comment by Scully66** [comment]
Sorry for the delay in responding.

 

The issue appears to have been resolved when Plex finally updated the new version information.  After that the update ran as expected.

 

Thanks for the information and your help,

 

Rod
