### ISSUE TITLE
Error when having $ (dollar sign) in password

### ISSUE THREAD

**Issue by nubje** [mrworf/plexupdate#25]
Hello!

I am getting **Error: Username and/or password incorrect** when using your script.
My password has all the crazy characters in it ($, @, &, !, %), so I did some testing and it seems like the URL encode (?) can't handle $ (dollar signs), because when I remove that it works perfectly.

A quick fix for me would be to remove the dollar signs from my password, but I am wondering if there is any other way to do it

Ubuntu 14.10 (Linux server 3.16.0-43-generic)

**Comment by mrworf** [comment]
Try enclosing it in single quotes instead. 

/Henric

**Comment by nubje** [comment]
That works perfectly - thank you! :)
