### ISSUE TITLE
support new raspberry pi release

### ISSUE THREAD

**Issue by si458** [mrworf/plexupdate#253]
update installer to support NEW OFFICIAL arm releases from plex (mainly for raspberry pi)

https://www.plex.tv/en-gb/media-server-downloads/#plex-media-server

https://downloads.plex.tv/plex-media-server-new/1.15.1.780-a27ffa5be/debian/plexmediaserver_1.15.1.780-a27ffa5be_armhf.deb

it appears the 5.json file from plex is returning the BUILD as `linux-armv7hf_neon`
instead of `linux-armv7l`, not sure why?

**Comment by demonbane** [comment]
Since Plex is providing actual builds now, this could be added but it's definitely non-trivial. If you'd like to take a shot at it and submit a PR I'd be happy to review the code, but I don't have a raspberry pi to test with unfortunately.
