### ISSUE TITLE
It's not running for me on Ubuntu

### ISSUE THREAD

**Issue by xcom169** [mrworf/plexupdate#254]
Error: Retrieving list of available distributions
ERROR: Unable to retrieve the URL needed for download (Query DISTRO: ubuntu, BUILD: linux-ubuntu-x86_64)

**Comment by sPaCeMoNk3yIam** [comment]
Same problem here.

**Comment by monkey113** [comment]
I also run into this problem on Ubuntu.

```
sudo bash plexupdate.sh
Retrieving list of available distributions
ERROR: Unable to retrieve the URL needed for download (Query DISTRO: ubuntu, BUILD: linux-ubuntu-x86_64)
```

**Comment by demonbane** [comment]
This is usually just a temporary issue on Plex's side so try it one more time. If it fails again, please re-run plexupdate with the `-v` option and provide the output here. Thanks.

**Comment by antigravity83** [comment]
Getting same issue here:

```
Retrieving list of available distributions
RELEASE=
DOWNLOAD=
CHECKSUM=
ERROR: Unable to retrieve the URL needed for download (Query DISTRO: ubuntu, BUILD: linux-ubuntu-x86_64)
```

**Comment by sPaCeMoNk3yIam** [comment]
When listing availablr distros, plexupdate expects not to have "_ubuntu" within the name for debian releases. So script should get a fix? Or am I wrong?

**Comment by demonbane** [comment]
Looks like the Plex team just pushed out an update that they [had mentioned last month](https://forums.plex.tv/t/linux-download-link-is-still-for-1-14/372535/59), but never gave an exact date for. I have a fix ready to go, just need to finish testing. Should be out within the hour.

**Comment by sPaCeMoNk3yIam** [comment]
Very nice work and response time. Can confirm that it works again! 🎉

**Comment by antigravity83** [comment]
Working here too - thank you very much
