### ISSUE TITLE
Ubuntu 32bit version not updating (plexpass)

### ISSUE THREAD

**Issue by smurphos** [mrworf/plexupdate#255]
Hi,

I think this might be because the current plex filename format appends i386 not i686 to the filename.

```steve@mint-toshiba ~ $ sudo /opt/plexupdate/plexupdate.sh -v
Fetching token from Plex server
Retrieving list of available distributions
RELEASE=
DOWNLOAD=
CHECKSUM=
ERROR: Unable to retrieve the URL needed for download (Query DISTRO: debian, BUILD: linux-i686)
```

Current plexpass version - https://downloads.plex.tv/plex-media-server-new/1.15.2.793-782228f99/debian/plexmediaserver_1.15.2.793-782228f99_i386.deb

**Comment by demonbane** [comment]
It's going to take a few days to figure out a good solution for this. I don't want to hard code the architecture, but I need to find something that will work across different systems fairly consistently.

A temporary fix that will allow you to keep updating while I'm working on it is to just add the following two lines to your `plexupdate.conf`:

```
BUILD='linux-x86'
DISTRO='debian'
```

**Comment by SquanchOn** [comment]
for debian also need to add the line DISTRO_INSTALL='dpkg -i' otherwise the update doesn't work in debian (or didn't for me anyway!)

**Comment by didyouexpectthat** [comment]
If you're using a newer version of Debian (8 or above), you can use `DISTRO_INSTALL='apt install'`  as apt (not apt-get) installs deb files now. :D
