### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by Mathyn** [mrworf/plexupdate#256]
I know how to uninstall Plex but how do I properly uninstall this tool from my system (Ubuntu)? Which are the pitfalls I should be aware of especially when auto updating is enabled?

**Comment by RobertSmits** [comment]
If you have PlexUpdate installed with the default configuration following files and folders are created,
and uninstalling should be as simple as removing them.

 - the main program folder 
  `/opt/plexupdate`
 - for configuration
  `/etc/plexupdate.conf`
  `/etc/plexupdate.cron.conf`
 - for auto updates
  `/etc/cron.daily/plexupdate`

Note:
If wget or git weren't installed during setup, these dependencies were auto installed.
You can remove these if no other application depends on them, but personally I wouldn't bother.

**Comment by Mathyn** [comment]
Great thanks!
