### ISSUE TITLE
Running and Install update at specific time like sunday 2AM?

### ISSUE THREAD

**Issue by jauyzed** [mrworf/plexupdate#258]
Hello,

This script is great but while installing, It would be great if there is a way to install downloaded plex server update at specific time. I have liveTV recordings going on and everytime plex server restarts, it builds the TV schedule which takes a sometime. It would be ideal to run for plex server update at 2am sunday. At these times, It doesn't matter if users are logged out or if server is in use.  

Thanks for this automation!

**Comment by demonbane** [comment]
If you used the installer script, it will run whenever your system runs `cron-daily` tasks. If you want to run it at 2 am on Sunday, you can just remove the symlink from `/etc/cron.daily` and add a cron entry to run `/opt/plexupdate/extras/cronwrapper` at 2 am. Alternately, you can move the symlink to `/etc/cron.weekly` but this will depend on when your system actually executes weekly tasks. (On my system, it's at 6:47am on Sunday.)
