### ISSUE TITLE
Server 127.0.0.1 is currently being used by one or more users, skipping installation. Please run again later

### ISSUE THREAD

**Issue by mlamoure** [mrworf/plexupdate#260]
I've recently started to see this message occur.  I saw that it was an issue in the past but had been fixed.  Any insight on how to fix it?  It's happening when manually executing plexupdate while I can see that there is no server usage.  I've been getting around it by manually shutting down the server, running plexupdate, and starting.

Error in log:

$ sudo ./plexupdate.sh 
Retrieving list of available distributions
File already exists (plexmediaserver_1.15.5.994-4610c6e8d_amd64.deb), won't download.
ERROR: Server 127.0.0.1 is currently being used by one or more users, skipping installation. Please run again later

**Comment by didyouexpectthat** [comment]
I'm getting this as well. I noticed it the other day and I temporarily worked around it by restarting Plex before I ran the update. 
![image](https://user-images.githubusercontent.com/1329077/57002763-8b5dbd00-6b76-11e9-8be9-24c23497e38f.png)


This is the part it fails at:


```
++ wget --no-check-certificate -q -O - 'https://127.0.0.1:32400/status/sessions?X-Plex-Token=TOKEN'
+ DATA='<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>'
+ RET=0
++ wget --no-check-certificate -q -O - 'https://127.0.0.1:32400/livetv/sessions?X-Plex-Token=TOKEN'
+ DATA+='<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="79">
...
+ '[' 0 -eq 0 ']'
++ awk '-F"' '/<MediaContainer size="[0-9]+">/ {count+=$2}; /<Player[^>]* state="paused"/ {count--}; END {print count}'
+ local mediacount=79
+ '[' '' = yes ']'
+ '[' 79 -gt 0 ']'
+ return 0
+ error 'Server 127.0.0.1 is currently being used by one or more users, skipping installation. Please run again later'
+ echo 'ERROR: Server 127.0.0.1 is currently being used by one or more users, skipping installation. Please run again later'
ERROR: Server 127.0.0.1 is currently being used by one or more users, skipping installation. Please run again later
+ exit 6
+ cleanup
+ rm /tmp/plexupdate.sha.k53p /tmp/plexupdate.wget.KeWt
```

**Comment by mlamoure** [comment]
Yes, I do use the DVR on my box as well.

**Comment by demonbane** [comment]
Based on the output provided by @didyouexpectthat, this looks like an issue with Plex itself. Plex is reporting that there are a lot of active streams which is why plexupdate is aborting the update. Any objections to closing out this issue?

**Comment by mlamoure** [comment]
I'm experiencing this regularly and consistently.  How can I help provide output to debug?

**Comment by demonbane** [comment]
Just run plexupdate with the `-v` option and it should provide a message saying:

`Activity check reports a count of ##, based on return data of: ...`

(except with a number and actual data)

**Comment by didyouexpectthat** [comment]
I haven't had too much time to research this new behavior on Plex yet... Maybe I will have some free-time this weekend and see what I can find out. If this is a new behavior of Plex (like when using Plex DVR), there may be some way to accommodate in plexupdate. I have no interest in stopping my recordings of Judge Judy so I am determined to find a way to understand why this is happening now. 😄

**Comment by didyouexpectthat** [comment]
I opened a thread on the Plex forums to inquire. I have 131 right now and my server is dead... and I trolled the logs but nothing substantial popped out (didn't see it spawn any new connections at least...). 
https://forums.plex.tv/t/livetv-sessions-returns-mediacontainer-size-of-131-when-idle/418223

**Comment by aporzio1** [comment]
I don't use the DVR very often, so I don't care if it gets interrupted. I also run the script at 3am and not much chance of something being recorded then. 

I commented out this line and its updates fine for me now

`#DATA+="$(wget -q -O - http://$1:$2/livetv/sessions)"`

**Comment by demonbane** [comment]
@aporzio1 while that does work, it's overkill. :) You can just remove the `PLEXSERVER` and `PLEXPORT` lines from your config and it won't bother to do the check anymore.

**Comment by aporzio1** [comment]
@demonbane won't that stop the check completely though? I would still like for it to postpone the update is something is being watched. I just don't care about the tuners.

**Comment by demonbane** [comment]
I was looking at the code figuring out if there's a better way to do this, but short of creating yet another setting (which we've really been trying to avoid for a while now), I think your solution is the best bet until we find out what's happening with Plex here.

**Comment by breezytm** [comment]
Any idea when we'll have something to test? This is script as been working great for so long.

**Comment by didyouexpectthat** [comment]
For the time being, I did what @demonbane suggested which is remove `PLEXSERVER` and `PLEXPORT` from the config. I haven't heard anything back from the kind folk of the Plex Forums.  I do my checks at 6:25 AM. This is being treated as a problem with Plex, not a problem with `plexupdate` unless the people at Plex have something different to suggest (perhaps a toggle in the config). The logs from Plex didn't explain (to me) why it is spawning these instances.

**Comment by didyouexpectthat** [comment]
I am currently on `1.16.1.1273-4b6101f87` and I have had Plex running for 2 days. 
```
root@rn628x:~# wget --no-check-certificate -q -O - 'https://127.0.0.1:32400/livetv/sessions?X-Plex-Token=$mytoken'
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>
```
So this is looking better... I am going to re-enable my `PLEXSERVER` and `PLEXPORT` and monitor longer.

**Comment by didyouexpectthat** [comment]
Following up again. plexupdate is working as expected since the last message. I am currently on `1.16.2.1297-4b7ace214` and it is all automatic. 
```
root@rn628x:~# wget --no-check-certificate -q -O - 'https://127.0.0.1:32400/livetv/sessions?X-Plex-Token=$token'; dpkg --list | grep -i plexmediaserver
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>
ii  plexmediaserver                1.16.2.1297-4b7ace214            amd64        Plex organizes all of your personal media so you can easily access and enjoy it.
root@rn628x:~#
```

I have also been getting live recordings as expected. I suggest we move this issue to closed. Plex was at fault, not the script.

**Comment by breezytm** [comment]
What you guys are saying is to upgrade to 1.16.1 and then It will start working afterwards?

**Comment by didyouexpectthat** [comment]
Hi @breezytm, it should be sufficient to go to 1.16.1 or newer to relieve yourself of this problem.  I haven't run into this problem since before 1.16.1. if you have this problem right now, restart Plex, then use plexupdate to upgrade to latest. 

@miamoure, can you kindly close this bug? Thanks.

**Comment by mrtumnus** [comment]
I'm still seeing this on 1.16.1.1291.  The 1.16.2 update is out, but plexupdate gives the error in the description.  Passing -v to plexupdate.sh shows several livetv sessions.

**Comment by didyouexpectthat** [comment]
@mrtumnus, can you verify in `Plex Media Server.log` whether you see those livetv/session IDs sitting at the transcoder idle?

**Comment by didyouexpectthat** [comment]
For kicks and giggles, I started a stream 
```
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="1">
<Video guid="plex://livetv/session/84515e4b-4dba-4e11-a039-8a0e77460d62" type="clip" title="Live Session " summary="" index="1" ratingCount="0" genuineMediaAnalysis="1" key="/livetv/sessions/84515e4b-4dba-4e11-a039-8a0e77460d62" live="1">
<Media container="mpegts" origin="livetv" uuid="84515e4b-4dba-4e11-a039-8a0e77460d62">
</Media>
</Video>
</MediaContainer>
```
I exited it, and then checked again
```
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>
```

So I am not having any sticky sessions and `idle` no longer appears in any of my PMS logs.

**Comment by didyouexpectthat** [comment]
@mrtumnus I saw your comments on Plex forums after I tried to also manually increase the count. :P

Plex says in 1.16.1 they made changes to livetv functionality. When I got onto 1.16.1, I did delete my scheduled recording and readded it (Judge Judy 😄). Maybe that was helpful/beneficial.
![image](https://user-images.githubusercontent.com/1329077/60744272-0aca8c80-9f2a-11e9-8511-dadc9a5d7cc7.png)

**Comment by mrtumnus** [comment]
> @mrtumnus, can you verify in `Plex Media Server.log` whether you see those livetv/session IDs sitting at the transcoder idle? And how many do you see?

I just checked again today (after updating to 1.16.2.1297), and I have 4 idle, "sticky" sessions just sitting there.  I can find two of them by UUID in "Plex Transcoder Statistics.log", but not "Plex Media Server.log".  Then again, I don't have verbose or debug logging turned on.
