### ISSUE TITLE
Running into issue on new install

### ISSUE THREAD

**Issue by jwaltrip4** [mrworf/plexupdate#269]

**Comment by jwaltrip4** [comment]
Been loving this.... 
However, Just updated to new server.  Downloaded this to new server, and it is not working.

and am getting this message:

Retrieving list of available distributions
Your OS reports the latest version of Plex (1.18.4.2164-2aa83397b) is already installed. Use -f to force download.

does not seem to find new versions.

want to be updating to Beta versions

**Comment by Steve8291** [comment]
What distro are you running?
Did you manually add your plex-token to the config file yet?
If you are on Ubuntu you may need to run the following from a non-root account inside the plexupdate directory:
```
cd /usr/local/plexupdate
sudo -u <your_user_name_here> bash -c 'source plexupdate-core' get-plex-token
```
Add the token that is returned to `/etc/plexupdate.conf`
`TOKEN='<my_token>'`

**Comment by jwaltrip4** [comment]
It was characters in token.  Was able to fix.  I don't remember exactly how
but th I t there was a reddit post on it and that had info on it
