### ISSUE TITLE
Only public updates being checked.

### ISSUE THREAD

**Issue by cdanderson** [mrworf/plexupdate#270]
I used the installer script to configure. I have PlexPass, and when I log in with the Plex app, I receive the following message: "A Plex Media Server update is available for the server [redacted]! 1.18.4.2171"

plexupdate.conf:

```
AUTOINSTALL='yes'
PUBLIC='no'
AUTOUPDATE='yes'
```
plexupdate.sh -v output:

```
Fetching token from Plex server
Retrieving list of available distributions
RELEASE="label":"Ubuntu (16.04+) / Debian (8+) - Intel/AMD 64-bit","build":"linux-x86_64","distro":"debian","url":"https://downloads.plex.tv/plex-media-server-new/1.18.3.2156-349e9837e/debian/plexmediaserver_1.18.3.2156-349e9837e_amd64.deb","checksum":"91728eb5e713e88dddd1eda06f6abfb88da73d03"
DOWNLOAD=https://downloads.plex.tv/plex-media-server-new/1.18.3.2156-349e9837e/debian/plexmediaserver_1.18.3.2156-349e9837e_amd64.deb
CHECKSUM=91728eb5e713e88dddd1eda06f6abfb88da73d03
INSTALLED_VERSION=1.18.3.2156-349e9837e
FILE_VERSION=1.18.3.2156-349e9837e
Your OS reports the latest version of Plex (1.18.3.2156-349e9837e) is already installed. Use -f to force download.
```

Please let me know if there is any additional information that would be helpful in troubleshooting. Thank you!

**Comment by cdanderson** [comment]
If I manually fetch my token (via 'bash -c 'source plexupdate-core' get-plex-token') and store it in the .conf file, this works and I am able to get the PlexPass version with the update script.

**Comment by pjs5406** [comment]
Also same for me.  Only seems to be checking for public releases, but i have conf file set same
`AUTOINSTALL='yes'
PUBLIC='no'
AUTOUPDATE='yes'`
Receive same output of Your OS reports latest version of plex is already installed.  Plex web gui shows an update is available.

**Comment by iceman73** [comment]
I have the same issue, and I tried putting my plextoken in the conf file and my install still only checks the public release.

**Comment by jwaltrip4** [comment]
Having same issue. Token is in plexupdate.conf

still does not update to latest beta.

**Comment by mrtumnus** [comment]
I also have this issue.  I believe I have found a fix for this, currently submitted as a pull request (#271).  The token wasn't being found because the regex wasn't matching it properly.

**Comment by jwaltrip4** [comment]
OK.. sorry. Dumb questions:
I assume I can simply download the 'core' portion and copy to folder with plexupdate?
Will any autoupdate activity cause it to be overwritten? (Do I need to disable checkupdate, autoupdate?)

**Comment by mrtumnus** [comment]
Yeah, you can just copy the one file (plexupdate-core); that's all that changed.
If you have autoupdate enabled, I would imagine it would overwrite it with the author's version.
