### ISSUE TITLE
Download takes a very long time

### ISSUE THREAD

**Issue by nnleaf** [mrworf/plexupdate#275]
Hi, I'm running into a problem while trying to download the latest plex update file. 

I'm running Debian. When I initially installed it, the progress bar barely moved. After waiting an hour, it moved just a bit. Thought it might just be something odd, so I ran the install without downloading the update. 

I ran `sudo /opt/plexupdate/plexupdate.sh -P` to show a progress bar while downloading the file and it's the same as when I was installing it. 1014K  10.2KB/s    eta 2h 51m

I tried a regular `wget` to download the update file which went perfectly.

I did try moving it to the tmp folder and tried running the plexupdate.sh to see if it would notice it and it does! Running the install flag works wonderfully as well so I'd love to add this to my update script. If there are any logs or such you need, please ask.

**Comment by demonbane** [comment]
Hmm, that's really odd. The only thing I can think of would be some sort of network issue on their end. Just to be on the safe side, try running `sudo /opt/plexupdate/plexupdate.sh -v` and let's see if that gives us any useful information.

**Comment by nnleaf** [comment]
Hi, I tried a few troubleshooting steps this afternoon. I rebooted the server and tried a regular run of `sudo /opt/plexupdate/plexupdate.sh -P` and the status bar still hangs mid-way. It speeds up to about 12-13% then just hangs there. 

I deleted the incomplete file from the `/tmp` then tried `sudo /opt/plexupdate/plexupdate.sh -v` as you requested and this was the output. 
````Fetching token from Plex server
Retrieving list of available distributions
RELEASE="label":"Ubuntu (16.04+) / Debian (8+) - Intel/AMD 64-bit","build":"linux-x86_64","distro":"debian","url":"https://downloads.plex.tv/plex-media-server-new/1.19.3.2764-ef515a800/debian/plexmediaserver_1.19.3.2764-ef515a800_amd64.deb","checksum":"17de3f6444f571d7c441b04b0ff90799ee8784c4"
DOWNLOAD=https://downloads.plex.tv/plex-media-server-new/1.19.3.2764-ef515a800/debian/plexmediaserver_1.19.3.2764-ef515a800_amd64.deb
CHECKSUM=17de3f6444f571d7c441b04b0ff90799ee8784c4
INSTALLED_VERSION=1.19.1.2645-ccb6eb67e
FILE_VERSION=1.19.3.2764-ef515a800
Downloading release "plexmediaserver_1.19.3.2764-ef515a800_amd64.deb"
````

It just stayed like that for a good 10 minutes before I stopped it. I ran `sudo /opt/plexupdate/plexupdate.sh -vP` for a progress bar and the speed just bogs down to about 5KB/s after 12-13%. 

I just remembered that I actually use wget -4 to force an ipv4 download because of some misconfigured ipv6 settings on my end that I hadn't had time to look into. I will be spinning up another server to install Plex on tonight to check.

**Comment by nnleaf** [comment]
Hi, so I was testing settings again this evening and it does seem that it's something on my end that's not letting ipv6 through. It seemingly only affects wget so far... 

I can't seem to figure it out right now and I've been bypassing plex downloads by using `wget -4`, would there be a way to set plexupdate to only use the wget -4 flag?

**Comment by nnleaf** [comment]
I dug into the script a bit and saw there was a nice little configuration setting for wget options. :)

Closing this issue!

**Comment by demonbane** [comment]
Glad you got it figured out. If you run into any other problems let us know.
