### ISSUE TITLE
Can this script be modified for Docker?

### ISSUE THREAD

**Issue by modem7** [mrworf/plexupdate#281]
How difficult would it be to have this script modified for Docker for the PMSPlex image? 

So in this case: 

1. Variable for Plex container name
2. Script checks to see if there is an update, the same way it does now. 
3. If there is, checks Plex if there's any logged on users. 
4. If there is not, restarts container so it can grab latest update (PMSPlex doesn't update the image, it does the update process internally).

**Comment by demonbane** [comment]
We have no plans of adding docker support to plexupdate, but you could probably use some of the code in your own script to do what you want. I'll provide some links of places to look below:

> 2. Script checks to see if there is an update, the same way it does now.

[lines 383-391 of plexupdate.sh](https://github.com/mrworf/plexupdate/blob/master/plexupdate.sh#L383-L391).

> 3. If there is, checks Plex if there's any logged on users.

[lines 180-209 of plexupdate-core](https://github.com/mrworf/plexupdate/blob/master/plexupdate-core#L180-L207)
