### ISSUE TITLE
Specify cron download directory?

### ISSUE THREAD

**Issue by n1nj4888** [mrworf/plexupdate#282]
Hi there!
I can see there’s a command line option for plexupdate.sh as follows:

--dldir <path/to/where/you/want/files/downloaded/to> This is the folder that the files will be downloaded to.

I assume this overrides the default /tmp download directory but how is this changed for every plexupdate.sh execution via cron? For example I couldn’t find documentation of a “DLDIR” config item for /etc/plexupdate.conf?

Thanks!

**Comment by demonbane** [comment]
The variable name is `DOWNLOADDIR`, so you can just add something like `DOWNLOADDIR="/my/download/path"` to `plexupdate.conf`.
