### ISSUE TITLE
naming scheme for Raspberry Pi package / armv7 on Debian has been changed again by Plex

### ISSUE THREAD

**Issue by lisanet** [mrworf/plexupdate#287]
The naming scheme oaf the arm V7 package on Ubuntu/Debian has been changed again by the Plex team. It's now armv7neon instead of armv7hf_neon.

I've already created a pull request which fixes this issue. https://github.com/mrworf/plexupdate/pull/286#issue-662041873

**Comment by xeryax** [comment]
Thanks for this! I can verify that updating line 57 of plexupdate.sh to the following works:
` 57 [ "$ARCH" = "armv7l" ] && ARCH="armv7neon"`
