### ISSUE TITLE
install.sh script has a small logic bug

### ISSUE THREAD

**Issue by PabluskiNC** [mrworf/plexupdate#288]
Line 322:
Currently: elif [ ! -z "$SUDO_USER" ]; then

Should be: elif [ -z "$SUDO_USER" ]; then

**Comment by demonbane** [comment]
That is correct as it is. It could be rewritten with a `-n` instead of `! -z` but the logic is correct. It's testing to see if you launched the script as sudo (which you should **not** do). If `SUDO_USER` **is not empty**, that means that you **are** running as sudo so we throw an error and abort.

**Comment by PabluskiNC** [comment]
I see.

I did a “sudo bash” to get the root prompt, since in ubuntu it is customary to not login to root directly…

I tweaked it work in my environment – and it did a the job.

Thanks for responding. 

Thanks for the code, as well.

 

-PabluskiNC

**Comment by demonbane** [comment]
Did you try running it without sudo? If you just run it from a regular user shell (not `sudo bash`) it will automatically ask you for sudo permissions when it needs it and everything should work fine. If you were having a problem with that not happening, that could be a separate issue. If not, and you modified the line as you described above, you've probably ended up installing as root which isn't strictly a problem, but not the way it's intended to be installed.
