### ISSUE TITLE
Update during DVR quiet time

### ISSUE THREAD

**Issue by ke4roh** [mrworf/plexupdate#292]
TV comes in around the clock, and it's hard to say ahead of time when the DVR won't be running.  Watch for a time when the system isn't recording to perform an update.  (Apologies if this is already in - I checked docs but didn't get into code (yet)).

**Comment by demonbane** [comment]
This is already included. When installing plexupdate for the first time, you will be prompted with the following:
> When using the auto-install option, would you like to check if the server is in use before upgrading?

If you answer yes, and an update is found while the server is in use, including any DVR recording jobs, the update will not be installed at that time.
