### ISSUE TITLE
Resets service group

### ISSUE THREAD

**Issue by RemonVanNieuwenhuizen** [mrworf/plexupdate#296]
After every update I have to update /lib/systemd/system/plexmediaserver.service to the correct group otherwise plex doesn't have permission to my files.
Otherwise very great and useful script.

**Comment by JasonMaloney** [comment]
> After every update I have to update /lib/systemd/system/plexmediaserver.service to the correct group otherwise plex doesn't have permission to my files. Otherwise very great and useful script.

Hi @RemonVanNieuwenhuizen, the correct way to implement such a customization with systemd is to use an override file. The easiest way to create one is to run "sudo systemctl edit plexmediaserver.service" and specify your group override there.

Hope this helps!

**Comment by RemonVanNieuwenhuizen** [comment]
Thank you @JasonMaloney, I just read the same at the top of the plex plexmediaserver.service file and wanted to put it here :).

`[Service]
Group=media`

Would this be enough?
