### ISSUE TITLE
Feature Request: Make Installer Automation-Friendly

### ISSUE THREAD

**Issue by majorgear** [mrworf/plexupdate#300]
Using Ansible automation to install the script 
`- name: Install plexupdate tool
  shell: bash -c "$(wget -qO - https://raw.githubusercontent.com/mrworf/plexupdate/master/extras/installer.sh)"
  remote_user: root
  become: yes
  when:
    - not plexupdate_results.stat.isDir is defined
`
gives this error "This script will ask for sudo as necessary, but you should not run it as sudo" 

Which leads me to believe it cannot be run in non-interactive fashion. Is there a way to pass in the information needed for installation in an automated fashion so that it can be installed by config management tools such as my example Ansible task?

**Comment by demonbane** [comment]
The installer script is only meant to be used interactively. If you want to automate the installation you will want to follow the [manual installation instructions](https://github.com/mrworf/plexupdate/wiki/Manually-installing-plexupdate) instead. All the installer really does is the git installation of plexupdate followed by writing out your `plexupdate.conf`, which should be pretty easy to automate.
