### ISSUE TITLE
Where does it download the PMS installer to?

### ISSUE THREAD

**Issue by SawkeeReemo** [mrworf/plexupdate#305]
I just ran my first update tonight and it worked! Thanks! But I like to keep the installer files in case I need to roll back since I'm on beta. I went to the `/opt/plexupdate` directory, but it's not in there nor in `/opt/plexupdate/extras`. Any idea where I can find it?

**Comment by SawkeeReemo** [comment]
I found in the plexupdate.sh script this variable:
`DOWNLOADDIR="/tmp"`

Can I add that to the `plexupdate.conf` file like:
`DOWNLOADDIR='~/Documents/plexupdate'`
to have it override that setting?

**Comment by demonbane** [comment]
Exactly. Any environment variables in the script can also be put into `plexupdate.conf`. And all command-line parameters (in this case `--dldir`) just update the correct environment variable, in that order. So if you change the script, the conf file will override it, and if you change the conf file, the command-line parameters will override it.

**Comment by SawkeeReemo** [comment]
Amazing. Thank you! I appreciate the response.
