### ISSUE TITLE
Autoupdate recieves an error

### ISSUE THREAD

**Issue by gregoryduckworth** [mrworf/plexupdate#34]
When using the AUTOUPDATE functionality, setting ```AUTOUPDATE=yes``` I recieve the following error: 

```Auto updating...OK```
```plexupdate.sh: line 124: plexupdate.sh: command not found```

I'm using Ubuntu 14.04 64bit.

**Comment by mrworf** [comment]
How are you launching the script? From commandline, via another script, cron, etc.. ?

**Comment by gregoryduckworth** [comment]
This was found when launching it from the command line, however I got the same error when running a basic cron on the same file.

**Comment by AltonV** [comment]
I am also running ubuntu 14.04 64bit, but I haven't got this error

**Comment by gregoryduckworth** [comment]
The steps I had gone, was clone the repo, create the ~/.plexupdate file containing the various variables and then ran ```bash plexupdate.sh``` from the directory.

**Comment by mrworf** [comment]
There's the problem :)

It doesn't expect you to run with "bash plexupdate.sh" .. It assumes you're using "./plexupdate.sh" since it's executable and runs bash automatically

**Comment by gregoryduckworth** [comment]
You are right! Thanks, I'd been banging my head about it and forgot something so simple!

**Comment by mrworf** [comment]
I'm fixing this so noone else needs to suffer. It's possible to detect this use-case and notify user

**Comment by mrworf** [comment]
Next version will detect this scenario and deal with it appropriately by prefixing with /bin/bash

Thanks for reporting this.
