### ISSUE TITLE
 Authenticating...Error: Unable to obtain authentication token, page changed?

### ISSUE THREAD

**Issue by RacerBas** [mrworf/plexupdate#37]
So after the script has been running fine for like the last month this is suddenly happening. The login page didn't change as suggested though. Any ideas?

**Comment by AltonV** [comment]
It's working fine for me

**Comment by RacerBas** [comment]
That's good for you but it isn't for me, and I'd like to figure out how to fix it.

**Comment by devinslick** [comment]
What version of wget are you using?
Can you share the output from the following command?

wget --save-cookies /tmp/kaka --keep-session-cookies https://plex.tv/users/sign_in -O - 2>/dev/null

**Comment by RacerBas** [comment]
So I quickly ran the command and it says it cannot verify the certificate. I'll look into it tomorrow.

**Comment by mrworf** [comment]
Is the time and date correct on your machine? Ssl certificates can fail the check if your computer's time is outside of the validity of the certificate.

**Comment by RacerBas** [comment]
The time and date is correct.

**Comment by RacerBas** [comment]
I reconfigured ca-certificates and now it's working again. Thanks for the suggestions.
