### ISSUE TITLE
Looks for configuration in wrong directory

### ISSUE THREAD

**Issue by TravisCHoward** [mrworf/plexupdate#38]
Running as superuser is required to actually install updates in CentOS, but when this is done the script looks in the home directory of root rather than of the current user.

**Comment by TravisCHoward** [comment]
Perhaps the script should use $SUDO_USER, "who am I" or logname to grab the actual username rather than just ~.

**Comment by brombomb** [comment]
It'd be nice to have thie configurable as well.  I prefer to keep my conf files with their scripts, e.g. I'd like to keep my conf file at `~/.plex/plexupdate/.plexupdate` as `~/.plex` is my download dir.

**Comment by mrworf** [comment]
I have a fix for this which is more substantial. Will update in about a week
