### ISSUE TITLE
Autoinstall command for RPM-based distros

### ISSUE THREAD

**Issue by Djelibeybi** [mrworf/plexupdate#4]
First, great script. :) Just a note that "rpm -i" should be "rpm -u" (to upgrade the RPM) for an auto-upgrade. Though, it's probably best to use "yum localinstall $RPM" instead so that it can decide the correct action and pull any dependencies too.

**Comment by mrworf** [comment]
So instead of rpm -i "$filename" it should be yum localinstall "$filename" ? Just checking since I don't run a RPM based distro myself :)

**Comment by Djelibeybi** [comment]
Correct. Though, also happy to fork and send you a pull request if you'd prefer.

**Comment by mrworf** [comment]
I should have time to do it today, not a huge change :) Thanks!

**Comment by mrworf** [comment]
Finally committed :)
