### ISSUE TITLE
Detect current version to see if it needs an update

### ISSUE THREAD

**Issue by sufr3ak** [mrworf/plexupdate#40]
I'd love to see a basic function in the beginning that would check the web version against the current version to see if an update is needed.

CURRENTVER=`export LD_LIBRARY_PATH=/usr/lib/plexmediaserver; /usr/lib/plexmediaserver/Plex\ Media\ Server  --version | awk -F[v-] '{print($2)}'` would give the numeric string of the version.

**Comment by mrworf** [comment]
It actually already does this using the package manager info which is more reliable since they can change other files than the so file and release it as a new version.

**Comment by sufr3ak** [comment]
So it does, my bad!
