### ISSUE TITLE
download doesn't work

### ISSUE THREAD

**Issue by vgeannin** [mrworf/plexupdate#42]
I think plex team had made some modification on the plex pass web site:
now the release value must be set to RELEASE="64 bit" instead of 64-bit

regards

**Comment by mrworf** [comment]
Thanks, I'll look into it later today. 

/Henric

**Comment by mrworf** [comment]
Can you provide logs of the issue? I have no problems downloading using "64-bit"

**Comment by vgeannin** [comment]
in fact I have the pb when I try to down latest version from plexpass on ubuntu server 15.10

Vincent

**Comment by mrworf** [comment]
Can you provide the output from plexupdate.sh and also which parameters you give to the script?

**Comment by vgeannin** [comment]
here the log : 
root@clr:/opt/plexupdate# ./plexupdate.sh
Authenticating...OK
Finding download URL for 64-bit...OK
Sorry, page layout must have changed, I'm unable to retrieve the URL needed for download

**Comment by vgeannin** [comment]
and in the plex download file (html) : 
                  <a href="https://downloads.plex.tv/plex-media-server/0.9.15.4.1679-e4df231/plexmediaserver_0.9.15.4.1679-e4df231_amd64.deb" class="pbtn pbtn-md track-event track-metric" data-async-event="authenticated download" data-event-action="Ubuntu" data-event-category="Download-Media-Server" data-event-label="Ubuntu64" data-event-noninteraction="false" data-metric-action="pms" data-metric-category="download" data-metric-custom1="PC" data-metric-custom2="Ubuntu">**64 bits**</a>
                  <a href="https://downloads.plex.tv/plex-media-server/0.9.15.4.1679-e4df231/plexmediaserver_0.9.15.4.1679-e4df231_i386.deb" class="pbtn pbtn-md track-event track-metric" data-async-event="authenticated download" data-event-action="Ubuntu" data-event-category="Download-Media-Server" data-event-label="Ubuntu32" data-event-noninteraction="false" data-metric-action="pms" data-metric-category="download" data-metric-custom1="PC" data-metric-custom2="Ubuntu">**32 bits**</a>

**Comment by mrworf** [comment]
Could it be that you're getting a localized version of the page? I've rewritten the parser to avoid language. Please download the latest version and try again. You should see it trying to download "Ubuntu64" instead of 64-bit

**Comment by mrworf** [comment]
Please reopen this issue if you still have the problem, otherwise I'll assume that the changes I made solved it.

**Comment by vgeannin** [comment]
So I make a new test and I confirm the modification solve the PB

Thanks,
Vincent
PS: Sorry for the delay to test the new version

**Comment by mrworf** [comment]
Glad to hear it worked out :)
