### ISSUE TITLE
If you use .plexupdate config file and have problems updating plex...

### ISSUE THREAD

**Issue by andofrjando** [mrworf/plexupdate#43]
If you're using a `.plexupdate` configuration file in your home directory and that file specifies the release with `RELEASE=`, then be sure to change it from `RELEASE=64-bit` to `RELEASE=64`. Otherwise you'll get the error `Sorry, page layout must have changed, I'm unable to retrieve the URL needed for download`.

**Comment by mrworf** [comment]
Sorry about that, the change I made earlier today didn't consider that people might be overriding the RELEASE= flag. The newly pushed version should warn you and also abort if it's completely unsupported.

Again, sorry for the inconvenience, please pull the new version.

**Comment by andofrjando** [comment]
No problems. Just thought I'd put the simple solution up for people if they needed it. Thanks for the excellent script. :)
