### ISSUE TITLE
dpkg interrupts update installer if Plex config file is changed

### ISSUE THREAD

**Issue by jant90** [mrworf/plexupdate#51]
I would like to update Plex automatically on my Ubuntu server 14.04 from cron so for that your script comes in perfectly.

However I edited Plex' config file (/etc/default/plexmediaserver) to run Plex as a different user and that results in dpkg interrupting the installation process.

I ran your script as:
```
$ sudo plexupdate.sh -a -d -p -u
```
And I get the following message from dpkg:
```
Configuration file '/etc/default/plexmediaserver'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** plexmediaserver (Y/I/N/O/D/Z) [default=N] ?
```
I looked through the dpkg command line options hoping I could add one on line 333 of your script as to automatically skip the manual confirmation but I didn't find anything useful.

Is it possible for you to update the script so fully unattended Plex updates are possible in my situation as well? Or can you give me recommendations for it?

Thanks!

**Comment by mrworf** [comment]
I've added the REDHAT_INSTALL and DEBIAN_INSTALL options which allow you to override the default commandline for installing packages. That should allow you to do what you need. Please close if this solves your issue.

**Comment by jant90** [comment]
This is great, thank you for your work!

I hadn't found a suitable dpkg CLI option just yet but I think I need `--force-confdef` in order to skip the confirmation and go with the default N (from my first post) automatically. I was using the CLI options so I made .plexupdate file in /root containing `DEBIAN_INSTALL='dpkg --force-confdef -i`' among my other options and I'm fairly certain that should work.

However I can't update Plex at the moment because there is no new version available so I will just close this issue for now and if I run into problems when on the next Plex update I'll just reopen an issue.

Lastly just a tiny bug/typo report (I think): when running plexupdate.sh -h it outputs `p = Print download URL and exit` which should be `r = Print download URL and exit` I believe.
