### ISSUE TITLE
KEEP doesn't do anything

### ISSUE THREAD

**Issue by demonbane** [mrworf/plexupdate#52]
It looks like `KEEP` has been rendered useless since 170db366. Since `/tmp/kaka` is deleted on exit, there's really no option to keep your session anymore. I personally don't care all that much, so just removing it altogether would work. If you **want** to have it work I'm happy to send in a PR since I've already dug into the code to see why it's not working in the first place.

**Comment by mrworf** [comment]
Oups! I've fixed it now, thanks for letting me know.

**Comment by demonbane** [comment]
Thanks for the quick response! Unfortunately, this only fixes half of the problem. :)

The other half is the `else` on line 260 since it's a catch-all right now. That should be updated to `elif [ "$PUBLIC" != "no" ]; then`.

**Comment by mrworf** [comment]
Guess I don't test public enough. Sorry about that, I'll do a fix later tonight when I get home.
