### ISSUE TITLE
Error Installing 64-bit on ARM

### ISSUE THREAD

**Issue by Im-New-Here** [mrworf/plexupdate#55]
The package (64-bit) downloaded fine, but returned "ERROR: dpkg: error processing /root/plexmediaserver_0.9.16.4.1911-ee6e505_amd64.deb"

Apparently, my server has an ARM processor and the dpkg didn't like it.

See here --> [[img]http://i.imgur.com/S4PMZbV.png[/img]]([img]http://i.imgur.com/S4PMZbV.png[/img])

**Comment by mrworf** [comment]
Ah! Actually, I don't support different architectures just yet. It needs a different link, right now it's trying to install a i386 binary on a ARM :)

I'll look into that later this week. Thanks for letting me know.

**Comment by mrworf** [comment]
Try the latest version, using the DISTRO, BUILD and DISTRO_INSTALL you should be able to download ARM now. @Im-New-Here 

Please close if it works

**Comment by mrworf** [comment]
Closing the issue due to lack of activity, please try the new way of selecting version and file new issues if it's not working. Thanks.
