### ISSUE TITLE
Force conf override

### ISSUE THREAD

**Issue by anythingtechaus** [mrworf/plexupdate#57]
Ran the script with AUTOINSTALL=yes but got stuck waiting to replace plexmediaserver.conf

> Configuration file '/etc/init/plexmediaserver.conf'
>  ==> File on system created by you or by a script.
>  ==> File also in package provided by package maintainer.

Perhaps

```
Dpkg::Options {
   "--force-confdef";
   "--force-confold";
};
```

or similar, https://debian-handbook.info/browse/stable/sect.automatic-upgrades.html

**Comment by mrworf** [comment]
Actually, with the latest version, you can override DEBIAN_INSTALL or extend it to do this:

Just add this to your ```.plexupdate``` file:
```DEBIAN_INSTALL="${DEBIAN_INSTALL} --force-confdef --force-confold"```
and it will do what you want.

Please close issue if this solves your problem.

**Comment by mrworf** [comment]
Closing this, please reopen if it didn't solve the problem
