### ISSUE TITLE
Check plex current usage before updating

### ISSUE THREAD

**Issue by sufr3ak** [mrworf/plexupdate#59]
I'm currently using a wrapper script to validate that Plex is not in use before running this script. I utilize the plexwatch tool, but it would be cool if this had something built in. I may have modified your original script as well, to make it work smoother with the wrapper. Will check if you're interested

**Comment by hakong** [comment]
@sufr3ak check #63 for a mostly simple and easy solution.

**Comment by AltonV** [comment]
Your solution don't work for detecting direct plays.


Why not query the plex server?
https://github.com/Arcanemagus/plex-api/wiki/Sessions-Status


Like this
`wget --no-check-certificate -q -O - https://172.16.0.2:32400/status/sessions?X-Plex-Token=xxxxxxxxxxxxxxxxxxxxxxxxx | grep -q '<MediaContainer size="0">' && echo "not in use" || echo "in use"`

**Comment by hakong** [comment]
Ah, you're right. Just tested with direct play.
This works fine without a token:
```
wget --no-check-certificate -q -O - https://127.0.0.1:32400/status/sessions | grep -q '<MediaContainer size="0">' && echo "not in use" || echo "in use"
```

**Comment by sufr3ak** [comment]
I would go with a 1 or 0 output, (or any other option) just to make it easier to script.
playstatus=$(wget --no-check-certificate -q -O - https://127.0.0.1:32400/status/sessions | grep -q '<MediaContainer size="0">' && echo 0 || echo 1)

**Comment by AltonV** [comment]
actually there's no need for the echos, the grep help page says
`-q    Quiet. Return 0 if PATTERN is found, 1 otherwise`
I just used those because demonstration purposes

**Comment by sufr3ak** [comment]
That's true. I'm loading it into a variable to be further used. But I can easily load it into an IF/THEN
