### ISSUE TITLE
Username and password verification not working

### ISSUE THREAD

**Issue by PhAzE-Variance** [mrworf/plexupdate#60]
When grepping the raw data for 'Sign In</title' this will always not find it since that text string doesn't exist on the new website.

Better to search for 'Logout' to verify login success.

**Comment by mrworf** [comment]
Fixed in latest version, please confirm and close

**Comment by PhAzE-Variance** [comment]
Thanks, I will test it out.  Can I ask, in the new code you added:

wget --header "X-Plex-Client-Identifier: 4a745ae7-1839-e44e-1e42-aebfa578c865" --header "X-Plex-Product: Plex SSO" --load-cookies /tmp/kaka --save-cookies /tmp/kaka --keep-session-cookies "${URL_LOGIN}" --post-file=/tmp/postdata -q -S -O /tmp/failcause 2>/tmp/raw

What is X-Plex-Client-Identifier: 4a745ae7-1839-e44e-1e42-aebfa578c865 referring to and where did that value come from?

(Thanks for this awesome script also!)

**Comment by mrworf** [comment]
The identifier is taken from what Mozilla sends during the same login process. Without one it doesn't work, so I copied the one they use for the Plex SingleSignOn process.

**Comment by mrworf** [comment]
@PhAzE-Variance Please close issue if this solved your issue

**Comment by PhAzE-Variance** [comment]
Confirmed login works. Thanks mrworf!
