### ISSUE TITLE
script doesn't found update on plexpass channel

### ISSUE THREAD

**Issue by thenamelessthing** [mrworf/plexupdate#68]
when I run 
/plexupdate.sh -p -c -a 2>&1 1>/var/log/plexupdate

no new update are found. But on my server I got a message which say new update available!

I'm on the Plexpass channel..

**Comment by sjorge** [comment]
Yep, seems like they broke the layout again -_-

**Comment by Mawuena** [comment]
Me three !!!
They kind of are a pain the plex people.
@mrworf can you help us out please ?

**Comment by Tommatheussen** [comment]
I'm not sure why, but when I open the JSON url in 2 different browsers (both logged in), I get the new version in 1 browser, the old version in another. This might be in issue with cookies or something

**Comment by skar42** [comment]
Just spent a good 30 minutes looking at the code and testing it to make sure it was logging in OK. Seems fine but the URL returned isn't for the latest plexpass version. Then I came here and found this thread. Next time I'll just check here first if I find a problem. :)

**Comment by Tommatheussen** [comment]
Just created a fix on #69, maybe not best solution yet, but at least a working solution for now.
At the very least it'll provide some info to @mrworf on what the issue is ;)
