### ISSUE TITLE
Error: Download directory does not exist or is not a directory

### ISSUE THREAD

**Issue by blackley** [mrworf/plexupdate#71]
Hi all,

I am having problems with the configuration - i have the download folder set as ~/Downloads (the folder does exist), however I'm getting the error message - "Error: Download directory does not exist or is not a directory"

**Comment by mrworf** [comment]
Could it be you're running this using sudo? If so, ~ will refer to root's account, not your logged in account. Please try with an absolute path instead if using sudo.

**Comment by blackley** [comment]
I have tried both sudo and as user and have put both full path and ~.  Also i have been doing further testing and find that if i don't use the .plexupdate file and add the details to the script it works fine, however if using the .plexupdate file it fails everytime.

**Comment by blackley** [comment]
Some further investigation - If i add the details for additional advanced settings to the .plexupdate file then the download folder setting fail, however if i only have the email, password and download folder - then it appears to accept the download folder, however fails authentication.  If i don't use the .plexupdate file and put all the settings in the script - it works fine.

**Comment by mrworf** [comment]
That sounds really odd to me. This is what I have in my .plexupdate

```
EMAIL=<my email>
PASS="<something secret>"
DOWNLOADDIR="~/"
#AUTOINSTALL=yes
KEEP=yes
```

And it works... 

Check the following on your side:

1. Make sure EMAIL, PASS and DOWNLOADDIR values are enclosed with quotes
2. Doublecheck so your .plexupdate isn't in DOS format

An easy way to check for DOS format is:
```grep "$(echo -e "\r\n")" .plexupdate```

If it prints out all the lines, then your file is in DOS format which will not play nice with bash.

**Comment by blackley** [comment]
Thanks for the information - this issue is now resovled.
