### ISSUE TITLE
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-a17e99e': Directory not empty

### ISSUE THREAD

**Issue by rothbart837** [mrworf/plexupdate#72]
I get this error whenever I update using plexupdate.sh (obviously the hex value in the Plug-ins-a17e99e changes with each version.)  I have a YouTube plugin that for some reason never seems to be moved when I perform an update.  This is an Ubuntu PMS install and the permissions seem to match all the other plugins folders and I'm using sudo when running it.  

I can manually go in an do something like:

sudo mv /usr/lib/plexmediaserver/Resources/Plug-ins-a17e99e/* /usr/lib/plexmediaserver/Resources/Plug-ins-c093d0d/

and it moves fine, I can then safely delete /usr/lib/plexmediaserver/Resources/Plug-ins-a17e99e

Since the error appears to be from dpkg, I'm not sure why some plugins seem to be moved while this youtube one doesn't.  Any ideas?

I should mention that PMS is successfully updated, but since that YouTube plugin isn't moved over, it stops showing up under Channels after I update PMS (until I manually move it.)

**Comment by mrworf** [comment]
I would check the permissions on it and make sure it matches the rest of the plugins. Both permissions, user and group info. But yeah, this is not a plexupdate issue :)

**Comment by rothbart837** [comment]
The permissions, owner, and group match the other plugins... and I'm running plexupdate.sh via sudo

I just can't figure out how the other plugins get transferred over but YouTubeTV doesn't.  I'm not even sure why the Plug-ins-xxxxxx directory has to be uniquely named for the specific PMS build...

I'm current with the plugin too, so no changes to make there either... (https://github.com/kolsys/YouTubeTV.bundle)

**Comment by mrworf** [comment]
I would search/open a thread on plex.tv forums since that's the correctt place for this question. 

Closing this issue since it's not related to plexupdate.sh (do not have control of plex's internal scripts used during update).
