### ISSUE TITLE
ERROR: RELEASE keyword is deprecated, use DISTRO and BUILD

### ISSUE THREAD

**Issue by ezraholm50** [mrworf/plexupdate#74]
`ERROR: RELEASE keyword is deprecated, use DISTRO and BUILD`

Ubuntu 16.04

All of a sudden started getting this error. Any ideas?

Thanks for the useful update script!

**Comment by mrworf** [comment]
This means you've upgraded to the latest version and RELEASE is nolonger used. For most people, removing release will work fine (script detects 32 vs 64, deb vs rpm systems).

If removing it solves your problem, please close this issue. Thanks :)

**Comment by ezraholm50** [comment]
Thanks for the quick reply.
I've changed this:

`#if [ ! "${RELEASE}" = "" ]; then
#       echo "ERROR: RELEASE keyword is deprecated, use DISTRO and BUILD"
#       exit 255
#fi`

Then it complained about changes to the script, could not auto update, changed it to No in .plexupdate.

After that reports that I got the latest version (manually updated before it broke awaiting your reply)
So I guess it works.

This should do it right?
Thanks again for the useful script.

**Comment by mrworf** [comment]
In your .plexupdate file, remove the RELEASE line, do not edit the script itself :)

**Comment by ezraholm50** [comment]
Right, stated in the script, sorry, will change it back.

Thanks!

**Comment by mrworf** [comment]
No worries :) Just don't want you to have to do more work than necessary in the long run :-D Closing it now

**Comment by ezraholm50** [comment]
It works, moved the login credentials over to the .plexupdate. 
Changing it in plexupdate.sh gave the error that the file was edited and autoupdate could not run.

Works as it should now! Thanks again!
