### ISSUE TITLE
Plex Pass authentication failing

### ISSUE THREAD

**Issue by Keou0007** [mrworf/plexupdate#78]
Something is wrong with the plexpass authentication. Posts at the end of [this thread](https://forums.plex.tv/discussion/222567/plex-media-server-update-automation-download-page-url-change) explain that the new website has changed something and with the current script setup the failed authentication just returns the non plex pass version.

**Comment by mrworf** [comment]
I think this is old, it works fine now unless you're having issues? If you are, please make sure you've updated to the latest version.

**Comment by Keou0007** [comment]
I updated to the newest commit, but the public release is now the same as the plexpass release as of thismorning, so I'm not sure how to check if its working. If its working for you, then I'm sure its all good.

**Comment by mrworf** [comment]
Closing this, please file new issue if problem persists.
