### ISSUE TITLE
Error since upgrading Ubuntu 15.04 (support for Ubuntu 15.04)

### ISSUE THREAD

**Issue by arjankuijpers** [mrworf/plexupdate#8]
First to say, that this script is awesome and it makes plex on linux so much easier, thanks

I have updated my Linux server updated to Ubuntu 15.04.
I understand that Canonical changed the boot and service management.
And when running the script, im getting errors

stop: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused                           

Installing new version of config file /etc/default/plexmediaserver ...
Failed to execute operation: File exists

dpkg: error processing package plexmediaserver (--install):
 subprocess installed post-installation script returned error exit status 1

Errors were encountered while processing:
 plexmediaserver

**Comment by mrworf** [comment]
Are you running this as root? All I do once the package is downloaded is to run dpkg -i <name of the file> which should work, otherwise we need to talk to the plex dudes since that would mean that the deb package is broken for 15.04. Please let me know how it works out.

**Comment by arjankuijpers** [comment]
Yes, I run it with the sudo command, if that is what you mean.

**Comment by mrworf** [comment]
Oki. Have you tried installing it manually using the dpkg -i command and see if you get the same error? Because if you do, the I'm afraid the Plex guys have an issue with Ubuntu 15

**Comment by arjankuijpers** [comment]
install it with dpkg -i works correct, im afraid :(

**Comment by mrworf** [comment]
Cool :) Then I have something to work with ... just odd that it works outside and not inside since it's the same command. But I have some ideas. Will not have time to work on it until next week though. If you find any other useful info, please let me know (or if you have a fix ;))

**Comment by arjankuijpers** [comment]
I Will

**Comment by savoxis** [comment]
I had the same problem, it is a problem with the ubuntu package and some old config files not the script (http://ubuntuforums.org/showthread.php?t=2234797) 
I resolved this by moving (though you can probably delete) /etc/init.d/plexmediaserver

BTW, thanks for the script mrworf, found it today going to save me the weekly copy-pasta

**Comment by arjankuijpers** [comment]
On my Ubuntu installation there is no such directory.

**Comment by mrworf** [comment]
Just did a small update, don't know if it will make a difference, but please pull and try and let me know how it went.

**Comment by mrworf** [comment]
Just tried installing it (plexupdate with auto install) in a new 15.04 ubuntu and saw no issues. I'm closing this one and if this still is an issue, please reopen.

Thanks,
Henric
