### ISSUE TITLE
Cron mode doesn't really make sense

### ISSUE THREAD

**Issue by demonbane** [mrworf/plexupdate#84]
I'm struggling to understand what scenario -c is actually meant for.

Every cron implementation I've used just ignores exit codes completely, so -c would seem to have nothing at all to do with "cron". It looks like it was mostly meant to reconcile what @hakong wanted in #62 (which doesn't seem directly cron related to me) vs #73.

What I'm wanting to accomplish (without adding yet another command line option) is just a cron mode that only produces output when something has changed. If you have the latest version, no output. If you don't have the latest version, produce output on STDOUT. If there's an error (regardless of if there's a new version or not) produce output on STDERR.

This way, -q and -S actually become useful modifiers to -c, whereas they currently largely replace it. (running with -cq is functionally identical to running with -q inside cron).

I'm happy to send in a PR for this functionality, I just wanted to bring this up ahead of time to make sure that I'm not stepping on any toes by doing so (or missing something obvious).

**Comment by mrworf** [comment]
Cron mode essentially makes all non-error situations return 0 which is universal for success. Otherwise, if there isn't a new version, it returns a non-zero version so you can find out why it wasn't installed.

If you look closer at cronexit, cronmode takes all codes except 255 and make them return zero.

**Comment by demonbane** [comment]
I know what the option does, what I mean is that I don't understand the purpose of it. Cron doesn't care about exit codes, so how does obscuring all nonzero exits have anything to do with cron?

**Comment by hakong** [comment]
But systemd does. Either way I figured no output and an exit code of 0
makes sense if plex is at the latest version.

**Comment by mrworf** [comment]
I'm leaning towards @demonbane especially given that there was a telegram patch before was also rejected. You should really do a wrapper around this script if you intend to run it from systemd. While cronmode is useful for this particular case, it's highly misnamed and brings in a function which doesn't make any sense unless I intend to support all kinds of scenarios with specific options.

The -c mode can be accomplished by:
```
MSG=$(/some/path/plexupdate.sh -a 2>&1 )
if [ $? -lt 255 ]; then
  exit 0
fi
echo "${MSG}"
exit 1
```
This makes sure it stays neutral to specific system requirements

**Comment by demonbane** [comment]
What I'd propose is to bring some of the -C functionality back to -c (printing only actionable output), while maintaining the exit code "scrubbing" that -c currently has. This will allow it to be used by both systemd users and cron users, **and** the name will now at least make sense. And, as an added bonus, anyone who is currently using -cq will see zero change from their end.

I've already started working on the PR for it, so I'll send it in once I'm done with the one for #85.

**Comment by hakong** [comment]
Sounds good!
