### ISSUE TITLE
Get rid of -S

### ISSUE THREAD

**Issue by demonbane** [mrworf/plexupdate#85]
Just opening this as an issue before sending in a PR to see if there are any objections. -S seems completely unnecessary for experienced users, and dangerous for inexperienced ones. If you know what you're doing, `./plexupdate.sh -q 2>/dev/null` does exactly the same thing. If you don't know what you're doing, -S only serves to hide all possible output from you which seems like a terrible idea.

It looks like it was added in #53 with the comment "*Added a silent mode argument (because why not?)*", which just seems like the worst possible reason to ever add anything to a piece of software.

**Comment by hakong** [comment]
Second this. Seems useless.

**Comment by mrworf** [comment]
Agreed, will go as soon as I have a second over.
