### ISSUE TITLE
./plexupdate.sh: line 505: sudo: command not found

### ISSUE THREAD

**Issue by seebus** [mrworf/plexupdate#90]
While running the script as root on debian the following issue comes up:

./plexupdate.sh: line 505: sudo: command not found

If I go into line 505 and remove the sudo the download works...

Debian GNU/Linux 8

**Comment by mrworf** [comment]
Interesting, so your system does not have sudo?

**Comment by seebus** [comment]
Debian 8 does not have sudo by default: https://www.privateinternetaccess.com/forum/discussion/18063/debian-8-1-0-jessie-sudo-fix-not-installed-by-default

**Comment by mrworf** [comment]
Latest version removes unnecessary call to sudo, since AUTOINSTALL requires root access and checks for it. Please update and try again
