### ISSUE TITLE
Eternal AutoUpdate

### ISSUE THREAD

**Issue by trotskylenin** [mrworf/plexupdate#91]
When the autoupdate option (-u) is used the script keeps looking for updates in loop forever.

**Comment by mrworf** [comment]
Can you provide some more details? Do you have any .plexupdate file options I should know? When I tried with -u it worked fine. Maybe you have an old version (which had issues with auto update) ?

**Comment by mscreations** [comment]
I just managed to reproduce this issue. It happens if you combine the options together (eg -adu instead of -a -d -u).

**Comment by mrworf** [comment]
Solved it permanently now, old method was just dumb :) Please test and close if fixed.

**Comment by trotskylenin** [comment]
Exactly. It happens when i use just a single -. I'll update manually and
tell you if it works now. Thank you.

El 27/8/2016 15:37, "Henric Andersson" <notifications@github.com> escribió:

Solved it permanently now, old method was just dumb :) Please test and
close if fixed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrworf/plexupdate/issues/91#issuecomment-242933514>,
or mute
the thread

**Comment by trotskylenin** [comment]
It works fine now! Thank you very much. You can close this.
