### ISSUE TITLE
Server reported as in use while the servce is stopped.

### ISSUE THREAD

**Issue by bjay1404** [mrworf/plexupdate#94]
Hello,

I'm using commit # 482f1d2c5a73f437a2aa351a6c28b1b53068668e. 
When my PMS server is stopped, I still get the following error. Any ideas? 

My service 
root@plex:~/plexupdate# bash plexupdate.sh
Auto updating...OK
Authenticating...OK
Finding download URL to download...OK
File already exists (plexmediaserver_1.1.1.2675-d00866c_amd64.deb), won't download.
Server 127.0.0.1 is currently being used by one or more users, skipping installation. Please run again later

**Comment by bjay1404** [comment]
Using Ubuntu 14.04.5

**Comment by mrworf** [comment]
Should work now with the latest version, please update and try again

**Comment by mrworf** [comment]
Closing the issue, please reopen it if you're having problems.
