### ISSUE TITLE
AUTOINSTALL fails when run from cron

### ISSUE THREAD

**Issue by demonbane** [mrworf/plexupdate#97]
Just started noticing this a few days ago and I'm guessing it was just getting silently ignored before the change to output handling for -c:

```
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
```

The problem is that `PATH` doesn't include `/sbin` when running in cron. This can be fixed by the user by just redefining `PATH` inside their crontab, but that could possibly have unintended consequences with other jobs.

Since both of these are being called from within `dpkg`, we can't call them "correctly" from inside plexupdate, so that just leaves two options:

1. Use `hash` to manually point `ldconfig` and `start-stop-daemon` at `/sbin`. Doesn't affect the `PATH` or any other applications directly, but it could fail if `dpkg` tries to call something other than `ldconfig` or `start-stop-daemon`, or if it calls them from within a subshell.

2. `export` an updated `PATH` before running `DISTRO_INSTALL`. Should work regardless, but it could (theoretically) have unintended consequences elsewhere in the script. (it would only be set if running in cron mode, so it **should** be fine)

Any thoughts or pros/cons for either approach before I send in a PR? (I personally prefer option 1 but I think 2 might be more foolproof.)

**Comment by mrworf** [comment]
Hmm... #2 should be close to the same behavior as if you ran from a regular shell, so you shouldn't really get any more than you would running using sudo. hash sounds better but like you said, it won't be foolproof and it seems that debian based system have a tendency to differ a bit between distro.

Maybe check for ldconfig and if not found, add sbin and see if it works, if it still fails, abort?
